//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MVCMuncheese.srvMuncheese {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="srvMuncheese.IsrvMuncheese")]
    public interface IsrvMuncheese {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IsrvMuncheese/recInventario_PA", ReplyAction="http://tempuri.org/IsrvMuncheese/recInventario_PAResponse")]
        System.Collections.Generic.List<Entidades.recInventario_Result> recInventario_PA();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IsrvMuncheese/recInventario_PA", ReplyAction="http://tempuri.org/IsrvMuncheese/recInventario_PAResponse")]
        System.Threading.Tasks.Task<System.Collections.Generic.List<Entidades.recInventario_Result>> recInventario_PAAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IsrvMuncheese/recInventarioXId_PA", ReplyAction="http://tempuri.org/IsrvMuncheese/recInventarioXId_PAResponse")]
        Entidades.recInventarioxId_Result recInventarioXId_PA(int pId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IsrvMuncheese/recInventarioXId_PA", ReplyAction="http://tempuri.org/IsrvMuncheese/recInventarioXId_PAResponse")]
        System.Threading.Tasks.Task<Entidades.recInventarioxId_Result> recInventarioXId_PAAsync(int pId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IsrvMuncheese/insInventario_PA", ReplyAction="http://tempuri.org/IsrvMuncheese/insInventario_PAResponse")]
        bool insInventario_PA(Entidades.Inventario pInventario);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IsrvMuncheese/insInventario_PA", ReplyAction="http://tempuri.org/IsrvMuncheese/insInventario_PAResponse")]
        System.Threading.Tasks.Task<bool> insInventario_PAAsync(Entidades.Inventario pInventario);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IsrvMuncheese/modInventario_PA", ReplyAction="http://tempuri.org/IsrvMuncheese/modInventario_PAResponse")]
        bool modInventario_PA(Entidades.Inventario pInventario);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IsrvMuncheese/modInventario_PA", ReplyAction="http://tempuri.org/IsrvMuncheese/modInventario_PAResponse")]
        System.Threading.Tasks.Task<bool> modInventario_PAAsync(Entidades.Inventario pInventario);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IsrvMuncheese/delInventario_PA", ReplyAction="http://tempuri.org/IsrvMuncheese/delInventario_PAResponse")]
        bool delInventario_PA(Entidades.Inventario pInventario);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IsrvMuncheese/delInventario_PA", ReplyAction="http://tempuri.org/IsrvMuncheese/delInventario_PAResponse")]
        System.Threading.Tasks.Task<bool> delInventario_PAAsync(Entidades.Inventario pInventario);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IsrvMuncheese/recFacturas_PA", ReplyAction="http://tempuri.org/IsrvMuncheese/recFacturas_PAResponse")]
        System.Collections.Generic.List<Entidades.recFacturas_Result> recFacturas_PA();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IsrvMuncheese/recFacturas_PA", ReplyAction="http://tempuri.org/IsrvMuncheese/recFacturas_PAResponse")]
        System.Threading.Tasks.Task<System.Collections.Generic.List<Entidades.recFacturas_Result>> recFacturas_PAAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IsrvMuncheese/recFacturasXId_PA", ReplyAction="http://tempuri.org/IsrvMuncheese/recFacturasXId_PAResponse")]
        Entidades.recFacturaxId_Result recFacturasXId_PA(int pId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IsrvMuncheese/recFacturasXId_PA", ReplyAction="http://tempuri.org/IsrvMuncheese/recFacturasXId_PAResponse")]
        System.Threading.Tasks.Task<Entidades.recFacturaxId_Result> recFacturasXId_PAAsync(int pId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IsrvMuncheese/insFacturas_PA", ReplyAction="http://tempuri.org/IsrvMuncheese/insFacturas_PAResponse")]
        bool insFacturas_PA(Entidades.Facturas pFacturas);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IsrvMuncheese/insFacturas_PA", ReplyAction="http://tempuri.org/IsrvMuncheese/insFacturas_PAResponse")]
        System.Threading.Tasks.Task<bool> insFacturas_PAAsync(Entidades.Facturas pFacturas);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IsrvMuncheese/modFacturas_PA", ReplyAction="http://tempuri.org/IsrvMuncheese/modFacturas_PAResponse")]
        bool modFacturas_PA(Entidades.Facturas pFacturas);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IsrvMuncheese/modFacturas_PA", ReplyAction="http://tempuri.org/IsrvMuncheese/modFacturas_PAResponse")]
        System.Threading.Tasks.Task<bool> modFacturas_PAAsync(Entidades.Facturas pFacturas);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IsrvMuncheese/delFacturas_PA", ReplyAction="http://tempuri.org/IsrvMuncheese/delFacturas_PAResponse")]
        bool delFacturas_PA(Entidades.Facturas pFacturas);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IsrvMuncheese/delFacturas_PA", ReplyAction="http://tempuri.org/IsrvMuncheese/delFacturas_PAResponse")]
        System.Threading.Tasks.Task<bool> delFacturas_PAAsync(Entidades.Facturas pFacturas);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IsrvMuncheese/recUsuario", ReplyAction="http://tempuri.org/IsrvMuncheese/recUsuarioResponse")]
        Entidades.Usuarios recUsuario(string pUsrLogin);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IsrvMuncheese/recUsuario", ReplyAction="http://tempuri.org/IsrvMuncheese/recUsuarioResponse")]
        System.Threading.Tasks.Task<Entidades.Usuarios> recUsuarioAsync(string pUsrLogin);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IsrvMuncheese/recClientes_ENT", ReplyAction="http://tempuri.org/IsrvMuncheese/recClientes_ENTResponse")]
        System.Collections.Generic.List<Entidades.Clientes> recClientes_ENT();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IsrvMuncheese/recClientes_ENT", ReplyAction="http://tempuri.org/IsrvMuncheese/recClientes_ENTResponse")]
        System.Threading.Tasks.Task<System.Collections.Generic.List<Entidades.Clientes>> recClientes_ENTAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IsrvMuncheese/recClientesXId_ENT", ReplyAction="http://tempuri.org/IsrvMuncheese/recClientesXId_ENTResponse")]
        Entidades.Clientes recClientesXId_ENT(string pId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IsrvMuncheese/recClientesXId_ENT", ReplyAction="http://tempuri.org/IsrvMuncheese/recClientesXId_ENTResponse")]
        System.Threading.Tasks.Task<Entidades.Clientes> recClientesXId_ENTAsync(string pId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IsrvMuncheese/insClientes_ENT", ReplyAction="http://tempuri.org/IsrvMuncheese/insClientes_ENTResponse")]
        bool insClientes_ENT(Entidades.Clientes pClientes);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IsrvMuncheese/insClientes_ENT", ReplyAction="http://tempuri.org/IsrvMuncheese/insClientes_ENTResponse")]
        System.Threading.Tasks.Task<bool> insClientes_ENTAsync(Entidades.Clientes pClientes);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IsrvMuncheese/modClientes_ENT", ReplyAction="http://tempuri.org/IsrvMuncheese/modClientes_ENTResponse")]
        bool modClientes_ENT(Entidades.Clientes pClientes);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IsrvMuncheese/modClientes_ENT", ReplyAction="http://tempuri.org/IsrvMuncheese/modClientes_ENTResponse")]
        System.Threading.Tasks.Task<bool> modClientes_ENTAsync(Entidades.Clientes pClientes);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IsrvMuncheese/delClientes_ENT", ReplyAction="http://tempuri.org/IsrvMuncheese/delClientes_ENTResponse")]
        bool delClientes_ENT(Entidades.Clientes pClientes);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IsrvMuncheese/delClientes_ENT", ReplyAction="http://tempuri.org/IsrvMuncheese/delClientes_ENTResponse")]
        System.Threading.Tasks.Task<bool> delClientes_ENTAsync(Entidades.Clientes pClientes);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IsrvMuncheese/recCliente", ReplyAction="http://tempuri.org/IsrvMuncheese/recClienteResponse")]
        System.Collections.Generic.List<Entidades.recCliente_Result> recCliente();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IsrvMuncheese/recCliente", ReplyAction="http://tempuri.org/IsrvMuncheese/recClienteResponse")]
        System.Threading.Tasks.Task<System.Collections.Generic.List<Entidades.recCliente_Result>> recClienteAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IsrvMuncheese/recClientexId", ReplyAction="http://tempuri.org/IsrvMuncheese/recClientexIdResponse")]
        Entidades.recClientexId_Result recClientexId(string pId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IsrvMuncheese/recClientexId", ReplyAction="http://tempuri.org/IsrvMuncheese/recClientexIdResponse")]
        System.Threading.Tasks.Task<Entidades.recClientexId_Result> recClientexIdAsync(string pId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IsrvMuncheese/insCliente", ReplyAction="http://tempuri.org/IsrvMuncheese/insClienteResponse")]
        bool insCliente(Entidades.Clientes pClientes);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IsrvMuncheese/insCliente", ReplyAction="http://tempuri.org/IsrvMuncheese/insClienteResponse")]
        System.Threading.Tasks.Task<bool> insClienteAsync(Entidades.Clientes pClientes);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IsrvMuncheese/modCliente", ReplyAction="http://tempuri.org/IsrvMuncheese/modClienteResponse")]
        bool modCliente(Entidades.Clientes pClientes);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IsrvMuncheese/modCliente", ReplyAction="http://tempuri.org/IsrvMuncheese/modClienteResponse")]
        System.Threading.Tasks.Task<bool> modClienteAsync(Entidades.Clientes pClientes);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IsrvMuncheese/delCliente", ReplyAction="http://tempuri.org/IsrvMuncheese/delClienteResponse")]
        bool delCliente(Entidades.Clientes pClientes);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IsrvMuncheese/delCliente", ReplyAction="http://tempuri.org/IsrvMuncheese/delClienteResponse")]
        System.Threading.Tasks.Task<bool> delClienteAsync(Entidades.Clientes pClientes);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IsrvMuncheese/recProveedores_PA", ReplyAction="http://tempuri.org/IsrvMuncheese/recProveedores_PAResponse")]
        System.Collections.Generic.List<Entidades.recProveedor_Result> recProveedores_PA();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IsrvMuncheese/recProveedores_PA", ReplyAction="http://tempuri.org/IsrvMuncheese/recProveedores_PAResponse")]
        System.Threading.Tasks.Task<System.Collections.Generic.List<Entidades.recProveedor_Result>> recProveedores_PAAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IsrvMuncheese/recProveedoresXId_PA", ReplyAction="http://tempuri.org/IsrvMuncheese/recProveedoresXId_PAResponse")]
        Entidades.recProveedorxId_Result recProveedoresXId_PA(int pId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IsrvMuncheese/recProveedoresXId_PA", ReplyAction="http://tempuri.org/IsrvMuncheese/recProveedoresXId_PAResponse")]
        System.Threading.Tasks.Task<Entidades.recProveedorxId_Result> recProveedoresXId_PAAsync(int pId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IsrvMuncheese/insProveedores_PA", ReplyAction="http://tempuri.org/IsrvMuncheese/insProveedores_PAResponse")]
        bool insProveedores_PA(Entidades.Proveedor pProveedores);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IsrvMuncheese/insProveedores_PA", ReplyAction="http://tempuri.org/IsrvMuncheese/insProveedores_PAResponse")]
        System.Threading.Tasks.Task<bool> insProveedores_PAAsync(Entidades.Proveedor pProveedores);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IsrvMuncheese/modProveedores_PA", ReplyAction="http://tempuri.org/IsrvMuncheese/modProveedores_PAResponse")]
        bool modProveedores_PA(Entidades.Proveedor pProveedores);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IsrvMuncheese/modProveedores_PA", ReplyAction="http://tempuri.org/IsrvMuncheese/modProveedores_PAResponse")]
        System.Threading.Tasks.Task<bool> modProveedores_PAAsync(Entidades.Proveedor pProveedores);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IsrvMuncheese/delProveedores_PA", ReplyAction="http://tempuri.org/IsrvMuncheese/delProveedores_PAResponse")]
        bool delProveedores_PA(Entidades.Proveedor pProveedores);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IsrvMuncheese/delProveedores_PA", ReplyAction="http://tempuri.org/IsrvMuncheese/delProveedores_PAResponse")]
        System.Threading.Tasks.Task<bool> delProveedores_PAAsync(Entidades.Proveedor pProveedores);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IsrvMuncheese/recIngredientes_PA", ReplyAction="http://tempuri.org/IsrvMuncheese/recIngredientes_PAResponse")]
        System.Collections.Generic.List<Entidades.recIngredientes_Result> recIngredientes_PA();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IsrvMuncheese/recIngredientes_PA", ReplyAction="http://tempuri.org/IsrvMuncheese/recIngredientes_PAResponse")]
        System.Threading.Tasks.Task<System.Collections.Generic.List<Entidades.recIngredientes_Result>> recIngredientes_PAAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IsrvMuncheese/recIngredientesXId_PA", ReplyAction="http://tempuri.org/IsrvMuncheese/recIngredientesXId_PAResponse")]
        Entidades.recIngredientexId_Result recIngredientesXId_PA(int pId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IsrvMuncheese/recIngredientesXId_PA", ReplyAction="http://tempuri.org/IsrvMuncheese/recIngredientesXId_PAResponse")]
        System.Threading.Tasks.Task<Entidades.recIngredientexId_Result> recIngredientesXId_PAAsync(int pId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IsrvMuncheese/insIngredientes_PA", ReplyAction="http://tempuri.org/IsrvMuncheese/insIngredientes_PAResponse")]
        bool insIngredientes_PA(Entidades.Ingredientes pIngredientes);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IsrvMuncheese/insIngredientes_PA", ReplyAction="http://tempuri.org/IsrvMuncheese/insIngredientes_PAResponse")]
        System.Threading.Tasks.Task<bool> insIngredientes_PAAsync(Entidades.Ingredientes pIngredientes);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IsrvMuncheese/modIngredientes_PA", ReplyAction="http://tempuri.org/IsrvMuncheese/modIngredientes_PAResponse")]
        bool modIngredientes_PA(Entidades.Ingredientes pIngredientes);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IsrvMuncheese/modIngredientes_PA", ReplyAction="http://tempuri.org/IsrvMuncheese/modIngredientes_PAResponse")]
        System.Threading.Tasks.Task<bool> modIngredientes_PAAsync(Entidades.Ingredientes pIngredientes);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IsrvMuncheese/delIngredientes_PA", ReplyAction="http://tempuri.org/IsrvMuncheese/delIngredientes_PAResponse")]
        bool delIngredientes_PA(Entidades.Ingredientes pIngredientes);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IsrvMuncheese/delIngredientes_PA", ReplyAction="http://tempuri.org/IsrvMuncheese/delIngredientes_PAResponse")]
        System.Threading.Tasks.Task<bool> delIngredientes_PAAsync(Entidades.Ingredientes pIngredientes);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IsrvMuncheese/recProductos_ENT", ReplyAction="http://tempuri.org/IsrvMuncheese/recProductos_ENTResponse")]
        System.Collections.Generic.List<Entidades.Productos> recProductos_ENT();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IsrvMuncheese/recProductos_ENT", ReplyAction="http://tempuri.org/IsrvMuncheese/recProductos_ENTResponse")]
        System.Threading.Tasks.Task<System.Collections.Generic.List<Entidades.Productos>> recProductos_ENTAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IsrvMuncheese/recProductosXId_ENT", ReplyAction="http://tempuri.org/IsrvMuncheese/recProductosXId_ENTResponse")]
        Entidades.Productos recProductosXId_ENT(int pId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IsrvMuncheese/recProductosXId_ENT", ReplyAction="http://tempuri.org/IsrvMuncheese/recProductosXId_ENTResponse")]
        System.Threading.Tasks.Task<Entidades.Productos> recProductosXId_ENTAsync(int pId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IsrvMuncheese/insProductos_ENT", ReplyAction="http://tempuri.org/IsrvMuncheese/insProductos_ENTResponse")]
        bool insProductos_ENT(Entidades.Productos pProductos);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IsrvMuncheese/insProductos_ENT", ReplyAction="http://tempuri.org/IsrvMuncheese/insProductos_ENTResponse")]
        System.Threading.Tasks.Task<bool> insProductos_ENTAsync(Entidades.Productos pProductos);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IsrvMuncheese/modProductos_ENT", ReplyAction="http://tempuri.org/IsrvMuncheese/modProductos_ENTResponse")]
        bool modProductos_ENT(Entidades.Productos pProductos);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IsrvMuncheese/modProductos_ENT", ReplyAction="http://tempuri.org/IsrvMuncheese/modProductos_ENTResponse")]
        System.Threading.Tasks.Task<bool> modProductos_ENTAsync(Entidades.Productos pProductos);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IsrvMuncheese/delProductos_ENT", ReplyAction="http://tempuri.org/IsrvMuncheese/delProductos_ENTResponse")]
        bool delProductos_ENT(Entidades.Productos pProductos);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IsrvMuncheese/delProductos_ENT", ReplyAction="http://tempuri.org/IsrvMuncheese/delProductos_ENTResponse")]
        System.Threading.Tasks.Task<bool> delProductos_ENTAsync(Entidades.Productos pProductos);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IsrvMuncheese/recTipo_Producto_ENT", ReplyAction="http://tempuri.org/IsrvMuncheese/recTipo_Producto_ENTResponse")]
        System.Collections.Generic.List<Entidades.Tipo_Producto> recTipo_Producto_ENT();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IsrvMuncheese/recTipo_Producto_ENT", ReplyAction="http://tempuri.org/IsrvMuncheese/recTipo_Producto_ENTResponse")]
        System.Threading.Tasks.Task<System.Collections.Generic.List<Entidades.Tipo_Producto>> recTipo_Producto_ENTAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IsrvMuncheese/recTipo_ProductoXId_ENT", ReplyAction="http://tempuri.org/IsrvMuncheese/recTipo_ProductoXId_ENTResponse")]
        Entidades.Tipo_Producto recTipo_ProductoXId_ENT(int pId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IsrvMuncheese/recTipo_ProductoXId_ENT", ReplyAction="http://tempuri.org/IsrvMuncheese/recTipo_ProductoXId_ENTResponse")]
        System.Threading.Tasks.Task<Entidades.Tipo_Producto> recTipo_ProductoXId_ENTAsync(int pId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IsrvMuncheese/insTipo_Producto_ENT", ReplyAction="http://tempuri.org/IsrvMuncheese/insTipo_Producto_ENTResponse")]
        bool insTipo_Producto_ENT(Entidades.Tipo_Producto pTipo_Producto);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IsrvMuncheese/insTipo_Producto_ENT", ReplyAction="http://tempuri.org/IsrvMuncheese/insTipo_Producto_ENTResponse")]
        System.Threading.Tasks.Task<bool> insTipo_Producto_ENTAsync(Entidades.Tipo_Producto pTipo_Producto);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IsrvMuncheese/modTipo_Producto_ENT", ReplyAction="http://tempuri.org/IsrvMuncheese/modTipo_Producto_ENTResponse")]
        bool modTipo_Producto_ENT(Entidades.Tipo_Producto pTipo_Producto);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IsrvMuncheese/modTipo_Producto_ENT", ReplyAction="http://tempuri.org/IsrvMuncheese/modTipo_Producto_ENTResponse")]
        System.Threading.Tasks.Task<bool> modTipo_Producto_ENTAsync(Entidades.Tipo_Producto pTipo_Producto);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IsrvMuncheese/delTipo_Producto_ENT", ReplyAction="http://tempuri.org/IsrvMuncheese/delTipo_Producto_ENTResponse")]
        bool delTipo_Producto_ENT(Entidades.Tipo_Producto pTipo_Producto);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IsrvMuncheese/delTipo_Producto_ENT", ReplyAction="http://tempuri.org/IsrvMuncheese/delTipo_Producto_ENTResponse")]
        System.Threading.Tasks.Task<bool> delTipo_Producto_ENTAsync(Entidades.Tipo_Producto pTipo_Producto);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IsrvMuncheese/recTipo_Producto_PA", ReplyAction="http://tempuri.org/IsrvMuncheese/recTipo_Producto_PAResponse")]
        System.Collections.Generic.List<Entidades.recTipo_Producto_Result> recTipo_Producto_PA();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IsrvMuncheese/recTipo_Producto_PA", ReplyAction="http://tempuri.org/IsrvMuncheese/recTipo_Producto_PAResponse")]
        System.Threading.Tasks.Task<System.Collections.Generic.List<Entidades.recTipo_Producto_Result>> recTipo_Producto_PAAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IsrvMuncheese/recTipo_ProductoXId_PA", ReplyAction="http://tempuri.org/IsrvMuncheese/recTipo_ProductoXId_PAResponse")]
        Entidades.recTipo_ProductoxId_Result recTipo_ProductoXId_PA(int pId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IsrvMuncheese/recTipo_ProductoXId_PA", ReplyAction="http://tempuri.org/IsrvMuncheese/recTipo_ProductoXId_PAResponse")]
        System.Threading.Tasks.Task<Entidades.recTipo_ProductoxId_Result> recTipo_ProductoXId_PAAsync(int pId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IsrvMuncheese/insTipo_Producto_PA", ReplyAction="http://tempuri.org/IsrvMuncheese/insTipo_Producto_PAResponse")]
        bool insTipo_Producto_PA(Entidades.Tipo_Producto pTipo_Producto);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IsrvMuncheese/insTipo_Producto_PA", ReplyAction="http://tempuri.org/IsrvMuncheese/insTipo_Producto_PAResponse")]
        System.Threading.Tasks.Task<bool> insTipo_Producto_PAAsync(Entidades.Tipo_Producto pTipo_Producto);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IsrvMuncheese/modTipo_Producto_PA", ReplyAction="http://tempuri.org/IsrvMuncheese/modTipo_Producto_PAResponse")]
        bool modTipo_Producto_PA(Entidades.Tipo_Producto pTipo_Producto);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IsrvMuncheese/modTipo_Producto_PA", ReplyAction="http://tempuri.org/IsrvMuncheese/modTipo_Producto_PAResponse")]
        System.Threading.Tasks.Task<bool> modTipo_Producto_PAAsync(Entidades.Tipo_Producto pTipo_Producto);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IsrvMuncheese/delTipo_Producto_PA", ReplyAction="http://tempuri.org/IsrvMuncheese/delTipo_Producto_PAResponse")]
        bool delTipo_Producto_PA(Entidades.Tipo_Producto pTipo_Producto);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IsrvMuncheese/delTipo_Producto_PA", ReplyAction="http://tempuri.org/IsrvMuncheese/delTipo_Producto_PAResponse")]
        System.Threading.Tasks.Task<bool> delTipo_Producto_PAAsync(Entidades.Tipo_Producto pTipo_Producto);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IsrvMuncheese/recIngredienteXProducto_PA", ReplyAction="http://tempuri.org/IsrvMuncheese/recIngredienteXProducto_PAResponse")]
        System.Collections.Generic.List<Entidades.recIngredientesXProducto_Result> recIngredienteXProducto_PA();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IsrvMuncheese/recIngredienteXProducto_PA", ReplyAction="http://tempuri.org/IsrvMuncheese/recIngredienteXProducto_PAResponse")]
        System.Threading.Tasks.Task<System.Collections.Generic.List<Entidades.recIngredientesXProducto_Result>> recIngredienteXProducto_PAAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IsrvMuncheese/recIngredienteXProductoXId_PA", ReplyAction="http://tempuri.org/IsrvMuncheese/recIngredienteXProductoXId_PAResponse")]
        Entidades.recIngredienteXProductoxId_Result recIngredienteXProductoXId_PA(int pId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IsrvMuncheese/recIngredienteXProductoXId_PA", ReplyAction="http://tempuri.org/IsrvMuncheese/recIngredienteXProductoXId_PAResponse")]
        System.Threading.Tasks.Task<Entidades.recIngredienteXProductoxId_Result> recIngredienteXProductoXId_PAAsync(int pId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IsrvMuncheese/insIngredienteXProducto_PA", ReplyAction="http://tempuri.org/IsrvMuncheese/insIngredienteXProducto_PAResponse")]
        bool insIngredienteXProducto_PA(Entidades.Ingredientes_X_Producto pIngredienteXProducto);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IsrvMuncheese/insIngredienteXProducto_PA", ReplyAction="http://tempuri.org/IsrvMuncheese/insIngredienteXProducto_PAResponse")]
        System.Threading.Tasks.Task<bool> insIngredienteXProducto_PAAsync(Entidades.Ingredientes_X_Producto pIngredienteXProducto);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IsrvMuncheese/modIngredienteXProducto_PA", ReplyAction="http://tempuri.org/IsrvMuncheese/modIngredienteXProducto_PAResponse")]
        bool modIngredienteXProducto_PA(Entidades.Ingredientes_X_Producto pIngredienteXProducto);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IsrvMuncheese/modIngredienteXProducto_PA", ReplyAction="http://tempuri.org/IsrvMuncheese/modIngredienteXProducto_PAResponse")]
        System.Threading.Tasks.Task<bool> modIngredienteXProducto_PAAsync(Entidades.Ingredientes_X_Producto pIngredienteXProducto);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IsrvMuncheese/delIngredienteXProducto_PA", ReplyAction="http://tempuri.org/IsrvMuncheese/delIngredienteXProducto_PAResponse")]
        bool delIngredienteXProducto_PA(Entidades.Ingredientes_X_Producto pIngredienteXProducto);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IsrvMuncheese/delIngredienteXProducto_PA", ReplyAction="http://tempuri.org/IsrvMuncheese/delIngredienteXProducto_PAResponse")]
        System.Threading.Tasks.Task<bool> delIngredienteXProducto_PAAsync(Entidades.Ingredientes_X_Producto pIngredienteXProducto);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IsrvMuncheese/recEstado_PA", ReplyAction="http://tempuri.org/IsrvMuncheese/recEstado_PAResponse")]
        System.Collections.Generic.List<Entidades.recEstados_Result> recEstado_PA();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IsrvMuncheese/recEstado_PA", ReplyAction="http://tempuri.org/IsrvMuncheese/recEstado_PAResponse")]
        System.Threading.Tasks.Task<System.Collections.Generic.List<Entidades.recEstados_Result>> recEstado_PAAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IsrvMuncheese/recEstadoXId_PA", ReplyAction="http://tempuri.org/IsrvMuncheese/recEstadoXId_PAResponse")]
        Entidades.recEstadoxId_Result recEstadoXId_PA(int pId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IsrvMuncheese/recEstadoXId_PA", ReplyAction="http://tempuri.org/IsrvMuncheese/recEstadoXId_PAResponse")]
        System.Threading.Tasks.Task<Entidades.recEstadoxId_Result> recEstadoXId_PAAsync(int pId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IsrvMuncheese/insEstado_PA", ReplyAction="http://tempuri.org/IsrvMuncheese/insEstado_PAResponse")]
        bool insEstado_PA(Entidades.Estado pEstado);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IsrvMuncheese/insEstado_PA", ReplyAction="http://tempuri.org/IsrvMuncheese/insEstado_PAResponse")]
        System.Threading.Tasks.Task<bool> insEstado_PAAsync(Entidades.Estado pEstado);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IsrvMuncheese/modEstado_PA", ReplyAction="http://tempuri.org/IsrvMuncheese/modEstado_PAResponse")]
        bool modEstado_PA(Entidades.Estado pEstado);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IsrvMuncheese/modEstado_PA", ReplyAction="http://tempuri.org/IsrvMuncheese/modEstado_PAResponse")]
        System.Threading.Tasks.Task<bool> modEstado_PAAsync(Entidades.Estado pEstado);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IsrvMuncheese/delEstado_PA", ReplyAction="http://tempuri.org/IsrvMuncheese/delEstado_PAResponse")]
        bool delEstado_PA(Entidades.Estado pEstado);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IsrvMuncheese/delEstado_PA", ReplyAction="http://tempuri.org/IsrvMuncheese/delEstado_PAResponse")]
        System.Threading.Tasks.Task<bool> delEstado_PAAsync(Entidades.Estado pEstado);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IsrvMuncheese/recMesas_PA", ReplyAction="http://tempuri.org/IsrvMuncheese/recMesas_PAResponse")]
        System.Collections.Generic.List<Entidades.recMesas_Result> recMesas_PA();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IsrvMuncheese/recMesas_PA", ReplyAction="http://tempuri.org/IsrvMuncheese/recMesas_PAResponse")]
        System.Threading.Tasks.Task<System.Collections.Generic.List<Entidades.recMesas_Result>> recMesas_PAAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IsrvMuncheese/recMesaXId_PA", ReplyAction="http://tempuri.org/IsrvMuncheese/recMesaXId_PAResponse")]
        Entidades.recMesaxId_Result recMesaXId_PA(int pId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IsrvMuncheese/recMesaXId_PA", ReplyAction="http://tempuri.org/IsrvMuncheese/recMesaXId_PAResponse")]
        System.Threading.Tasks.Task<Entidades.recMesaxId_Result> recMesaXId_PAAsync(int pId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IsrvMuncheese/insMesas_PA", ReplyAction="http://tempuri.org/IsrvMuncheese/insMesas_PAResponse")]
        bool insMesas_PA(Entidades.Mesas pMesas);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IsrvMuncheese/insMesas_PA", ReplyAction="http://tempuri.org/IsrvMuncheese/insMesas_PAResponse")]
        System.Threading.Tasks.Task<bool> insMesas_PAAsync(Entidades.Mesas pMesas);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IsrvMuncheese/modMesas_PA", ReplyAction="http://tempuri.org/IsrvMuncheese/modMesas_PAResponse")]
        bool modMesas_PA(Entidades.Mesas pMesas);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IsrvMuncheese/modMesas_PA", ReplyAction="http://tempuri.org/IsrvMuncheese/modMesas_PAResponse")]
        System.Threading.Tasks.Task<bool> modMesas_PAAsync(Entidades.Mesas pMesas);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IsrvMuncheese/delMesas_PA", ReplyAction="http://tempuri.org/IsrvMuncheese/delMesas_PAResponse")]
        bool delMesas_PA(Entidades.Mesas pMesas);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IsrvMuncheese/delMesas_PA", ReplyAction="http://tempuri.org/IsrvMuncheese/delMesas_PAResponse")]
        System.Threading.Tasks.Task<bool> delMesas_PAAsync(Entidades.Mesas pMesas);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IsrvMuncheese/recOrdenes_PA", ReplyAction="http://tempuri.org/IsrvMuncheese/recOrdenes_PAResponse")]
        System.Collections.Generic.List<Entidades.recOrdenes_Result> recOrdenes_PA();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IsrvMuncheese/recOrdenes_PA", ReplyAction="http://tempuri.org/IsrvMuncheese/recOrdenes_PAResponse")]
        System.Threading.Tasks.Task<System.Collections.Generic.List<Entidades.recOrdenes_Result>> recOrdenes_PAAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IsrvMuncheese/recOrdenesXId_PA", ReplyAction="http://tempuri.org/IsrvMuncheese/recOrdenesXId_PAResponse")]
        Entidades.recOrdenxId_Result recOrdenesXId_PA(int pId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IsrvMuncheese/recOrdenesXId_PA", ReplyAction="http://tempuri.org/IsrvMuncheese/recOrdenesXId_PAResponse")]
        System.Threading.Tasks.Task<Entidades.recOrdenxId_Result> recOrdenesXId_PAAsync(int pId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IsrvMuncheese/insOrdenes_PAa", ReplyAction="http://tempuri.org/IsrvMuncheese/insOrdenes_PAaResponse")]
        bool insOrdenes_PAa(Entidades.Ordenes pOrdenes);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IsrvMuncheese/insOrdenes_PAa", ReplyAction="http://tempuri.org/IsrvMuncheese/insOrdenes_PAaResponse")]
        System.Threading.Tasks.Task<bool> insOrdenes_PAaAsync(Entidades.Ordenes pOrdenes);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IsrvMuncheese/recObtenerProductosPorCategoria_ResultXId_PA", ReplyAction="http://tempuri.org/IsrvMuncheese/recObtenerProductosPorCategoria_ResultXId_PAResp" +
            "onse")]
        Entidades.ObtenerProductosPorCategoria_Result recObtenerProductosPorCategoria_ResultXId_PA(int pId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IsrvMuncheese/recObtenerProductosPorCategoria_ResultXId_PA", ReplyAction="http://tempuri.org/IsrvMuncheese/recObtenerProductosPorCategoria_ResultXId_PAResp" +
            "onse")]
        System.Threading.Tasks.Task<Entidades.ObtenerProductosPorCategoria_Result> recObtenerProductosPorCategoria_ResultXId_PAAsync(int pId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IsrvMuncheese/ObtenerOrdenesDeMesa_PA", ReplyAction="http://tempuri.org/IsrvMuncheese/ObtenerOrdenesDeMesa_PAResponse")]
        Entidades.ObtenerOrdenesDeMesa_Result ObtenerOrdenesDeMesa_PA(int pId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IsrvMuncheese/ObtenerOrdenesDeMesa_PA", ReplyAction="http://tempuri.org/IsrvMuncheese/ObtenerOrdenesDeMesa_PAResponse")]
        System.Threading.Tasks.Task<Entidades.ObtenerOrdenesDeMesa_Result> ObtenerOrdenesDeMesa_PAAsync(int pId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IsrvMuncheese/recOrdenes_ENT", ReplyAction="http://tempuri.org/IsrvMuncheese/recOrdenes_ENTResponse")]
        System.Collections.Generic.List<Entidades.Ordenes> recOrdenes_ENT();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IsrvMuncheese/recOrdenes_ENT", ReplyAction="http://tempuri.org/IsrvMuncheese/recOrdenes_ENTResponse")]
        System.Threading.Tasks.Task<System.Collections.Generic.List<Entidades.Ordenes>> recOrdenes_ENTAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IsrvMuncheese/recOrdenesXId_ENT", ReplyAction="http://tempuri.org/IsrvMuncheese/recOrdenesXId_ENTResponse")]
        Entidades.Ordenes recOrdenesXId_ENT(int pId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IsrvMuncheese/recOrdenesXId_ENT", ReplyAction="http://tempuri.org/IsrvMuncheese/recOrdenesXId_ENTResponse")]
        System.Threading.Tasks.Task<Entidades.Ordenes> recOrdenesXId_ENTAsync(int pId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IsrvMuncheese/insOrdenes_ENT", ReplyAction="http://tempuri.org/IsrvMuncheese/insOrdenes_ENTResponse")]
        bool insOrdenes_ENT(Entidades.Ordenes pOrdenes);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IsrvMuncheese/insOrdenes_ENT", ReplyAction="http://tempuri.org/IsrvMuncheese/insOrdenes_ENTResponse")]
        System.Threading.Tasks.Task<bool> insOrdenes_ENTAsync(Entidades.Ordenes pOrdenes);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IsrvMuncheese/modOrdenes_ENT", ReplyAction="http://tempuri.org/IsrvMuncheese/modOrdenes_ENTResponse")]
        bool modOrdenes_ENT(Entidades.Ordenes pOrdenes);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IsrvMuncheese/modOrdenes_ENT", ReplyAction="http://tempuri.org/IsrvMuncheese/modOrdenes_ENTResponse")]
        System.Threading.Tasks.Task<bool> modOrdenes_ENTAsync(Entidades.Ordenes pOrdenes);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IsrvMuncheese/delOrdenes_ENT", ReplyAction="http://tempuri.org/IsrvMuncheese/delOrdenes_ENTResponse")]
        bool delOrdenes_ENT(Entidades.Ordenes pOrdenes);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IsrvMuncheese/delOrdenes_ENT", ReplyAction="http://tempuri.org/IsrvMuncheese/delOrdenes_ENTResponse")]
        System.Threading.Tasks.Task<bool> delOrdenes_ENTAsync(Entidades.Ordenes pOrdenes);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IsrvMuncheese/recDetalleOrden_PA", ReplyAction="http://tempuri.org/IsrvMuncheese/recDetalleOrden_PAResponse")]
        System.Collections.Generic.List<Entidades.recDetalleOrden_Result> recDetalleOrden_PA();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IsrvMuncheese/recDetalleOrden_PA", ReplyAction="http://tempuri.org/IsrvMuncheese/recDetalleOrden_PAResponse")]
        System.Threading.Tasks.Task<System.Collections.Generic.List<Entidades.recDetalleOrden_Result>> recDetalleOrden_PAAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IsrvMuncheese/recDetalleOrdenXId_PA", ReplyAction="http://tempuri.org/IsrvMuncheese/recDetalleOrdenXId_PAResponse")]
        Entidades.recDetalleOrdenxId_Result recDetalleOrdenXId_PA(int pId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IsrvMuncheese/recDetalleOrdenXId_PA", ReplyAction="http://tempuri.org/IsrvMuncheese/recDetalleOrdenXId_PAResponse")]
        System.Threading.Tasks.Task<Entidades.recDetalleOrdenxId_Result> recDetalleOrdenXId_PAAsync(int pId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IsrvMuncheese/insDetalleOrden_PA", ReplyAction="http://tempuri.org/IsrvMuncheese/insDetalleOrden_PAResponse")]
        bool insDetalleOrden_PA(Entidades.DetalleOrden pDetalleOrden);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IsrvMuncheese/insDetalleOrden_PA", ReplyAction="http://tempuri.org/IsrvMuncheese/insDetalleOrden_PAResponse")]
        System.Threading.Tasks.Task<bool> insDetalleOrden_PAAsync(Entidades.DetalleOrden pDetalleOrden);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IsrvMuncheese/modDetalleOrden_PA", ReplyAction="http://tempuri.org/IsrvMuncheese/modDetalleOrden_PAResponse")]
        bool modDetalleOrden_PA(Entidades.DetalleOrden pDetalleOrden);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IsrvMuncheese/modDetalleOrden_PA", ReplyAction="http://tempuri.org/IsrvMuncheese/modDetalleOrden_PAResponse")]
        System.Threading.Tasks.Task<bool> modDetalleOrden_PAAsync(Entidades.DetalleOrden pDetalleOrden);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IsrvMuncheese/delDetalleOrden_PA", ReplyAction="http://tempuri.org/IsrvMuncheese/delDetalleOrden_PAResponse")]
        bool delDetalleOrden_PA(Entidades.DetalleOrden pDetalleOrden);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IsrvMuncheese/delDetalleOrden_PA", ReplyAction="http://tempuri.org/IsrvMuncheese/delDetalleOrden_PAResponse")]
        System.Threading.Tasks.Task<bool> delDetalleOrden_PAAsync(Entidades.DetalleOrden pDetalleOrden);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IsrvMuncheese/recDetalleOrden_ENT", ReplyAction="http://tempuri.org/IsrvMuncheese/recDetalleOrden_ENTResponse")]
        System.Collections.Generic.List<Entidades.DetalleOrden> recDetalleOrden_ENT();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IsrvMuncheese/recDetalleOrden_ENT", ReplyAction="http://tempuri.org/IsrvMuncheese/recDetalleOrden_ENTResponse")]
        System.Threading.Tasks.Task<System.Collections.Generic.List<Entidades.DetalleOrden>> recDetalleOrden_ENTAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IsrvMuncheese/recDetalleOrdenXId_ENT", ReplyAction="http://tempuri.org/IsrvMuncheese/recDetalleOrdenXId_ENTResponse")]
        Entidades.DetalleOrden recDetalleOrdenXId_ENT(int pId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IsrvMuncheese/recDetalleOrdenXId_ENT", ReplyAction="http://tempuri.org/IsrvMuncheese/recDetalleOrdenXId_ENTResponse")]
        System.Threading.Tasks.Task<Entidades.DetalleOrden> recDetalleOrdenXId_ENTAsync(int pId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IsrvMuncheese/insDetalleOrden_ENT", ReplyAction="http://tempuri.org/IsrvMuncheese/insDetalleOrden_ENTResponse")]
        bool insDetalleOrden_ENT(Entidades.DetalleOrden pDetalleOrden);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IsrvMuncheese/insDetalleOrden_ENT", ReplyAction="http://tempuri.org/IsrvMuncheese/insDetalleOrden_ENTResponse")]
        System.Threading.Tasks.Task<bool> insDetalleOrden_ENTAsync(Entidades.DetalleOrden pDetalleOrden);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IsrvMuncheese/modDetalleOrden_ENT", ReplyAction="http://tempuri.org/IsrvMuncheese/modDetalleOrden_ENTResponse")]
        bool modDetalleOrden_ENT(Entidades.DetalleOrden pDetalleOrden);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IsrvMuncheese/modDetalleOrden_ENT", ReplyAction="http://tempuri.org/IsrvMuncheese/modDetalleOrden_ENTResponse")]
        System.Threading.Tasks.Task<bool> modDetalleOrden_ENTAsync(Entidades.DetalleOrden pDetalleOrden);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IsrvMuncheese/delDetalleOrden_ENT", ReplyAction="http://tempuri.org/IsrvMuncheese/delDetalleOrden_ENTResponse")]
        bool delDetalleOrden_ENT(Entidades.DetalleOrden pDetalleOrden);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IsrvMuncheese/delDetalleOrden_ENT", ReplyAction="http://tempuri.org/IsrvMuncheese/delDetalleOrden_ENTResponse")]
        System.Threading.Tasks.Task<bool> delDetalleOrden_ENTAsync(Entidades.DetalleOrden pDetalleOrden);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IsrvMuncheese/recPerfiles_PA", ReplyAction="http://tempuri.org/IsrvMuncheese/recPerfiles_PAResponse")]
        System.Collections.Generic.List<Entidades.recPerfiles_Result> recPerfiles_PA();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IsrvMuncheese/recPerfiles_PA", ReplyAction="http://tempuri.org/IsrvMuncheese/recPerfiles_PAResponse")]
        System.Threading.Tasks.Task<System.Collections.Generic.List<Entidades.recPerfiles_Result>> recPerfiles_PAAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IsrvMuncheese/recPerfilesXId_PA", ReplyAction="http://tempuri.org/IsrvMuncheese/recPerfilesXId_PAResponse")]
        Entidades.recMesaPerfilxId_Result recPerfilesXId_PA(int pId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IsrvMuncheese/recPerfilesXId_PA", ReplyAction="http://tempuri.org/IsrvMuncheese/recPerfilesXId_PAResponse")]
        System.Threading.Tasks.Task<Entidades.recMesaPerfilxId_Result> recPerfilesXId_PAAsync(int pId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IsrvMuncheese/insPerfiles_PA", ReplyAction="http://tempuri.org/IsrvMuncheese/insPerfiles_PAResponse")]
        bool insPerfiles_PA(Entidades.Perfiles pPerfiles);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IsrvMuncheese/insPerfiles_PA", ReplyAction="http://tempuri.org/IsrvMuncheese/insPerfiles_PAResponse")]
        System.Threading.Tasks.Task<bool> insPerfiles_PAAsync(Entidades.Perfiles pPerfiles);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IsrvMuncheese/modPerfiles_PA", ReplyAction="http://tempuri.org/IsrvMuncheese/modPerfiles_PAResponse")]
        bool modPerfiles_PA(Entidades.Perfiles pPerfiles);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IsrvMuncheese/modPerfiles_PA", ReplyAction="http://tempuri.org/IsrvMuncheese/modPerfiles_PAResponse")]
        System.Threading.Tasks.Task<bool> modPerfiles_PAAsync(Entidades.Perfiles pPerfiles);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IsrvMuncheese/delPerfiles_PA", ReplyAction="http://tempuri.org/IsrvMuncheese/delPerfiles_PAResponse")]
        bool delPerfiles_PA(Entidades.Perfiles pPerfiles);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IsrvMuncheese/delPerfiles_PA", ReplyAction="http://tempuri.org/IsrvMuncheese/delPerfiles_PAResponse")]
        System.Threading.Tasks.Task<bool> delPerfiles_PAAsync(Entidades.Perfiles pPerfiles);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IsrvMuncheese/recUsuarios_PA", ReplyAction="http://tempuri.org/IsrvMuncheese/recUsuarios_PAResponse")]
        System.Collections.Generic.List<Entidades.recUsuarios_Result> recUsuarios_PA();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IsrvMuncheese/recUsuarios_PA", ReplyAction="http://tempuri.org/IsrvMuncheese/recUsuarios_PAResponse")]
        System.Threading.Tasks.Task<System.Collections.Generic.List<Entidades.recUsuarios_Result>> recUsuarios_PAAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IsrvMuncheese/recUsuariosXId_PA", ReplyAction="http://tempuri.org/IsrvMuncheese/recUsuariosXId_PAResponse")]
        Entidades.recUsuarioxId_Result recUsuariosXId_PA(string pId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IsrvMuncheese/recUsuariosXId_PA", ReplyAction="http://tempuri.org/IsrvMuncheese/recUsuariosXId_PAResponse")]
        System.Threading.Tasks.Task<Entidades.recUsuarioxId_Result> recUsuariosXId_PAAsync(string pId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IsrvMuncheese/insUsuarios_PA", ReplyAction="http://tempuri.org/IsrvMuncheese/insUsuarios_PAResponse")]
        bool insUsuarios_PA(Entidades.Usuarios pUsuarios);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IsrvMuncheese/insUsuarios_PA", ReplyAction="http://tempuri.org/IsrvMuncheese/insUsuarios_PAResponse")]
        System.Threading.Tasks.Task<bool> insUsuarios_PAAsync(Entidades.Usuarios pUsuarios);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IsrvMuncheese/modUsuarios_PA", ReplyAction="http://tempuri.org/IsrvMuncheese/modUsuarios_PAResponse")]
        bool modUsuarios_PA(Entidades.Usuarios pUsuarios);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IsrvMuncheese/modUsuarios_PA", ReplyAction="http://tempuri.org/IsrvMuncheese/modUsuarios_PAResponse")]
        System.Threading.Tasks.Task<bool> modUsuarios_PAAsync(Entidades.Usuarios pUsuarios);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IsrvMuncheese/delUsuarios_PA", ReplyAction="http://tempuri.org/IsrvMuncheese/delUsuarios_PAResponse")]
        bool delUsuarios_PA(Entidades.Usuarios pUsuarios);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IsrvMuncheese/delUsuarios_PA", ReplyAction="http://tempuri.org/IsrvMuncheese/delUsuarios_PAResponse")]
        System.Threading.Tasks.Task<bool> delUsuarios_PAAsync(Entidades.Usuarios pUsuarios);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IsrvMuncheese/recPerfilUsuario_PA", ReplyAction="http://tempuri.org/IsrvMuncheese/recPerfilUsuario_PAResponse")]
        System.Collections.Generic.List<Entidades.recPerfilUsuario_Result> recPerfilUsuario_PA();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IsrvMuncheese/recPerfilUsuario_PA", ReplyAction="http://tempuri.org/IsrvMuncheese/recPerfilUsuario_PAResponse")]
        System.Threading.Tasks.Task<System.Collections.Generic.List<Entidades.recPerfilUsuario_Result>> recPerfilUsuario_PAAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IsrvMuncheese/recPerfilUsuarioXId_PA", ReplyAction="http://tempuri.org/IsrvMuncheese/recPerfilUsuarioXId_PAResponse")]
        Entidades.recPerfilUsuarioxId_Result recPerfilUsuarioXId_PA(int pId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IsrvMuncheese/recPerfilUsuarioXId_PA", ReplyAction="http://tempuri.org/IsrvMuncheese/recPerfilUsuarioXId_PAResponse")]
        System.Threading.Tasks.Task<Entidades.recPerfilUsuarioxId_Result> recPerfilUsuarioXId_PAAsync(int pId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IsrvMuncheese/insPerfilUsuario_PA", ReplyAction="http://tempuri.org/IsrvMuncheese/insPerfilUsuario_PAResponse")]
        bool insPerfilUsuario_PA(Entidades.PerfilUsuario pPerfilUsuario);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IsrvMuncheese/insPerfilUsuario_PA", ReplyAction="http://tempuri.org/IsrvMuncheese/insPerfilUsuario_PAResponse")]
        System.Threading.Tasks.Task<bool> insPerfilUsuario_PAAsync(Entidades.PerfilUsuario pPerfilUsuario);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IsrvMuncheese/modPerfilUsuario_PA", ReplyAction="http://tempuri.org/IsrvMuncheese/modPerfilUsuario_PAResponse")]
        bool modPerfilUsuario_PA(Entidades.PerfilUsuario pPerfilUsuario);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IsrvMuncheese/modPerfilUsuario_PA", ReplyAction="http://tempuri.org/IsrvMuncheese/modPerfilUsuario_PAResponse")]
        System.Threading.Tasks.Task<bool> modPerfilUsuario_PAAsync(Entidades.PerfilUsuario pPerfilUsuario);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IsrvMuncheese/delPerfilUsuario_PA", ReplyAction="http://tempuri.org/IsrvMuncheese/delPerfilUsuario_PAResponse")]
        bool delPerfilUsuario_PA(Entidades.PerfilUsuario pPerfilUsuario);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IsrvMuncheese/delPerfilUsuario_PA", ReplyAction="http://tempuri.org/IsrvMuncheese/delPerfilUsuario_PAResponse")]
        System.Threading.Tasks.Task<bool> delPerfilUsuario_PAAsync(Entidades.PerfilUsuario pPerfilUsuario);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IsrvMuncheeseChannel : MVCMuncheese.srvMuncheese.IsrvMuncheese, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class IsrvMuncheeseClient : System.ServiceModel.ClientBase<MVCMuncheese.srvMuncheese.IsrvMuncheese>, MVCMuncheese.srvMuncheese.IsrvMuncheese {
        
        public IsrvMuncheeseClient() {
        }
        
        public IsrvMuncheeseClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public IsrvMuncheeseClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public IsrvMuncheeseClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public IsrvMuncheeseClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public System.Collections.Generic.List<Entidades.recInventario_Result> recInventario_PA() {
            return base.Channel.recInventario_PA();
        }
        
        public System.Threading.Tasks.Task<System.Collections.Generic.List<Entidades.recInventario_Result>> recInventario_PAAsync() {
            return base.Channel.recInventario_PAAsync();
        }
        
        public Entidades.recInventarioxId_Result recInventarioXId_PA(int pId) {
            return base.Channel.recInventarioXId_PA(pId);
        }
        
        public System.Threading.Tasks.Task<Entidades.recInventarioxId_Result> recInventarioXId_PAAsync(int pId) {
            return base.Channel.recInventarioXId_PAAsync(pId);
        }
        
        public bool insInventario_PA(Entidades.Inventario pInventario) {
            return base.Channel.insInventario_PA(pInventario);
        }
        
        public System.Threading.Tasks.Task<bool> insInventario_PAAsync(Entidades.Inventario pInventario) {
            return base.Channel.insInventario_PAAsync(pInventario);
        }
        
        public bool modInventario_PA(Entidades.Inventario pInventario) {
            return base.Channel.modInventario_PA(pInventario);
        }
        
        public System.Threading.Tasks.Task<bool> modInventario_PAAsync(Entidades.Inventario pInventario) {
            return base.Channel.modInventario_PAAsync(pInventario);
        }
        
        public bool delInventario_PA(Entidades.Inventario pInventario) {
            return base.Channel.delInventario_PA(pInventario);
        }
        
        public System.Threading.Tasks.Task<bool> delInventario_PAAsync(Entidades.Inventario pInventario) {
            return base.Channel.delInventario_PAAsync(pInventario);
        }
        
        public System.Collections.Generic.List<Entidades.recFacturas_Result> recFacturas_PA() {
            return base.Channel.recFacturas_PA();
        }
        
        public System.Threading.Tasks.Task<System.Collections.Generic.List<Entidades.recFacturas_Result>> recFacturas_PAAsync() {
            return base.Channel.recFacturas_PAAsync();
        }
        
        public Entidades.recFacturaxId_Result recFacturasXId_PA(int pId) {
            return base.Channel.recFacturasXId_PA(pId);
        }
        
        public System.Threading.Tasks.Task<Entidades.recFacturaxId_Result> recFacturasXId_PAAsync(int pId) {
            return base.Channel.recFacturasXId_PAAsync(pId);
        }
        
        public bool insFacturas_PA(Entidades.Facturas pFacturas) {
            return base.Channel.insFacturas_PA(pFacturas);
        }
        
        public System.Threading.Tasks.Task<bool> insFacturas_PAAsync(Entidades.Facturas pFacturas) {
            return base.Channel.insFacturas_PAAsync(pFacturas);
        }
        
        public bool modFacturas_PA(Entidades.Facturas pFacturas) {
            return base.Channel.modFacturas_PA(pFacturas);
        }
        
        public System.Threading.Tasks.Task<bool> modFacturas_PAAsync(Entidades.Facturas pFacturas) {
            return base.Channel.modFacturas_PAAsync(pFacturas);
        }
        
        public bool delFacturas_PA(Entidades.Facturas pFacturas) {
            return base.Channel.delFacturas_PA(pFacturas);
        }
        
        public System.Threading.Tasks.Task<bool> delFacturas_PAAsync(Entidades.Facturas pFacturas) {
            return base.Channel.delFacturas_PAAsync(pFacturas);
        }
        
        public Entidades.Usuarios recUsuario(string pUsrLogin) {
            return base.Channel.recUsuario(pUsrLogin);
        }
        
        public System.Threading.Tasks.Task<Entidades.Usuarios> recUsuarioAsync(string pUsrLogin) {
            return base.Channel.recUsuarioAsync(pUsrLogin);
        }
        
        public System.Collections.Generic.List<Entidades.Clientes> recClientes_ENT() {
            return base.Channel.recClientes_ENT();
        }
        
        public System.Threading.Tasks.Task<System.Collections.Generic.List<Entidades.Clientes>> recClientes_ENTAsync() {
            return base.Channel.recClientes_ENTAsync();
        }
        
        public Entidades.Clientes recClientesXId_ENT(string pId) {
            return base.Channel.recClientesXId_ENT(pId);
        }
        
        public System.Threading.Tasks.Task<Entidades.Clientes> recClientesXId_ENTAsync(string pId) {
            return base.Channel.recClientesXId_ENTAsync(pId);
        }
        
        public bool insClientes_ENT(Entidades.Clientes pClientes) {
            return base.Channel.insClientes_ENT(pClientes);
        }
        
        public System.Threading.Tasks.Task<bool> insClientes_ENTAsync(Entidades.Clientes pClientes) {
            return base.Channel.insClientes_ENTAsync(pClientes);
        }
        
        public bool modClientes_ENT(Entidades.Clientes pClientes) {
            return base.Channel.modClientes_ENT(pClientes);
        }
        
        public System.Threading.Tasks.Task<bool> modClientes_ENTAsync(Entidades.Clientes pClientes) {
            return base.Channel.modClientes_ENTAsync(pClientes);
        }
        
        public bool delClientes_ENT(Entidades.Clientes pClientes) {
            return base.Channel.delClientes_ENT(pClientes);
        }
        
        public System.Threading.Tasks.Task<bool> delClientes_ENTAsync(Entidades.Clientes pClientes) {
            return base.Channel.delClientes_ENTAsync(pClientes);
        }
        
        public System.Collections.Generic.List<Entidades.recCliente_Result> recCliente() {
            return base.Channel.recCliente();
        }
        
        public System.Threading.Tasks.Task<System.Collections.Generic.List<Entidades.recCliente_Result>> recClienteAsync() {
            return base.Channel.recClienteAsync();
        }
        
        public Entidades.recClientexId_Result recClientexId(string pId) {
            return base.Channel.recClientexId(pId);
        }
        
        public System.Threading.Tasks.Task<Entidades.recClientexId_Result> recClientexIdAsync(string pId) {
            return base.Channel.recClientexIdAsync(pId);
        }
        
        public bool insCliente(Entidades.Clientes pClientes) {
            return base.Channel.insCliente(pClientes);
        }
        
        public System.Threading.Tasks.Task<bool> insClienteAsync(Entidades.Clientes pClientes) {
            return base.Channel.insClienteAsync(pClientes);
        }
        
        public bool modCliente(Entidades.Clientes pClientes) {
            return base.Channel.modCliente(pClientes);
        }
        
        public System.Threading.Tasks.Task<bool> modClienteAsync(Entidades.Clientes pClientes) {
            return base.Channel.modClienteAsync(pClientes);
        }
        
        public bool delCliente(Entidades.Clientes pClientes) {
            return base.Channel.delCliente(pClientes);
        }
        
        public System.Threading.Tasks.Task<bool> delClienteAsync(Entidades.Clientes pClientes) {
            return base.Channel.delClienteAsync(pClientes);
        }
        
        public System.Collections.Generic.List<Entidades.recProveedor_Result> recProveedores_PA() {
            return base.Channel.recProveedores_PA();
        }
        
        public System.Threading.Tasks.Task<System.Collections.Generic.List<Entidades.recProveedor_Result>> recProveedores_PAAsync() {
            return base.Channel.recProveedores_PAAsync();
        }
        
        public Entidades.recProveedorxId_Result recProveedoresXId_PA(int pId) {
            return base.Channel.recProveedoresXId_PA(pId);
        }
        
        public System.Threading.Tasks.Task<Entidades.recProveedorxId_Result> recProveedoresXId_PAAsync(int pId) {
            return base.Channel.recProveedoresXId_PAAsync(pId);
        }
        
        public bool insProveedores_PA(Entidades.Proveedor pProveedores) {
            return base.Channel.insProveedores_PA(pProveedores);
        }
        
        public System.Threading.Tasks.Task<bool> insProveedores_PAAsync(Entidades.Proveedor pProveedores) {
            return base.Channel.insProveedores_PAAsync(pProveedores);
        }
        
        public bool modProveedores_PA(Entidades.Proveedor pProveedores) {
            return base.Channel.modProveedores_PA(pProveedores);
        }
        
        public System.Threading.Tasks.Task<bool> modProveedores_PAAsync(Entidades.Proveedor pProveedores) {
            return base.Channel.modProveedores_PAAsync(pProveedores);
        }
        
        public bool delProveedores_PA(Entidades.Proveedor pProveedores) {
            return base.Channel.delProveedores_PA(pProveedores);
        }
        
        public System.Threading.Tasks.Task<bool> delProveedores_PAAsync(Entidades.Proveedor pProveedores) {
            return base.Channel.delProveedores_PAAsync(pProveedores);
        }
        
        public System.Collections.Generic.List<Entidades.recIngredientes_Result> recIngredientes_PA() {
            return base.Channel.recIngredientes_PA();
        }
        
        public System.Threading.Tasks.Task<System.Collections.Generic.List<Entidades.recIngredientes_Result>> recIngredientes_PAAsync() {
            return base.Channel.recIngredientes_PAAsync();
        }
        
        public Entidades.recIngredientexId_Result recIngredientesXId_PA(int pId) {
            return base.Channel.recIngredientesXId_PA(pId);
        }
        
        public System.Threading.Tasks.Task<Entidades.recIngredientexId_Result> recIngredientesXId_PAAsync(int pId) {
            return base.Channel.recIngredientesXId_PAAsync(pId);
        }
        
        public bool insIngredientes_PA(Entidades.Ingredientes pIngredientes) {
            return base.Channel.insIngredientes_PA(pIngredientes);
        }
        
        public System.Threading.Tasks.Task<bool> insIngredientes_PAAsync(Entidades.Ingredientes pIngredientes) {
            return base.Channel.insIngredientes_PAAsync(pIngredientes);
        }
        
        public bool modIngredientes_PA(Entidades.Ingredientes pIngredientes) {
            return base.Channel.modIngredientes_PA(pIngredientes);
        }
        
        public System.Threading.Tasks.Task<bool> modIngredientes_PAAsync(Entidades.Ingredientes pIngredientes) {
            return base.Channel.modIngredientes_PAAsync(pIngredientes);
        }
        
        public bool delIngredientes_PA(Entidades.Ingredientes pIngredientes) {
            return base.Channel.delIngredientes_PA(pIngredientes);
        }
        
        public System.Threading.Tasks.Task<bool> delIngredientes_PAAsync(Entidades.Ingredientes pIngredientes) {
            return base.Channel.delIngredientes_PAAsync(pIngredientes);
        }
        
        public System.Collections.Generic.List<Entidades.Productos> recProductos_ENT() {
            return base.Channel.recProductos_ENT();
        }
        
        public System.Threading.Tasks.Task<System.Collections.Generic.List<Entidades.Productos>> recProductos_ENTAsync() {
            return base.Channel.recProductos_ENTAsync();
        }
        
        public Entidades.Productos recProductosXId_ENT(int pId) {
            return base.Channel.recProductosXId_ENT(pId);
        }
        
        public System.Threading.Tasks.Task<Entidades.Productos> recProductosXId_ENTAsync(int pId) {
            return base.Channel.recProductosXId_ENTAsync(pId);
        }
        
        public bool insProductos_ENT(Entidades.Productos pProductos) {
            return base.Channel.insProductos_ENT(pProductos);
        }
        
        public System.Threading.Tasks.Task<bool> insProductos_ENTAsync(Entidades.Productos pProductos) {
            return base.Channel.insProductos_ENTAsync(pProductos);
        }
        
        public bool modProductos_ENT(Entidades.Productos pProductos) {
            return base.Channel.modProductos_ENT(pProductos);
        }
        
        public System.Threading.Tasks.Task<bool> modProductos_ENTAsync(Entidades.Productos pProductos) {
            return base.Channel.modProductos_ENTAsync(pProductos);
        }
        
        public bool delProductos_ENT(Entidades.Productos pProductos) {
            return base.Channel.delProductos_ENT(pProductos);
        }
        
        public System.Threading.Tasks.Task<bool> delProductos_ENTAsync(Entidades.Productos pProductos) {
            return base.Channel.delProductos_ENTAsync(pProductos);
        }
        
        public System.Collections.Generic.List<Entidades.Tipo_Producto> recTipo_Producto_ENT() {
            return base.Channel.recTipo_Producto_ENT();
        }
        
        public System.Threading.Tasks.Task<System.Collections.Generic.List<Entidades.Tipo_Producto>> recTipo_Producto_ENTAsync() {
            return base.Channel.recTipo_Producto_ENTAsync();
        }
        
        public Entidades.Tipo_Producto recTipo_ProductoXId_ENT(int pId) {
            return base.Channel.recTipo_ProductoXId_ENT(pId);
        }
        
        public System.Threading.Tasks.Task<Entidades.Tipo_Producto> recTipo_ProductoXId_ENTAsync(int pId) {
            return base.Channel.recTipo_ProductoXId_ENTAsync(pId);
        }
        
        public bool insTipo_Producto_ENT(Entidades.Tipo_Producto pTipo_Producto) {
            return base.Channel.insTipo_Producto_ENT(pTipo_Producto);
        }
        
        public System.Threading.Tasks.Task<bool> insTipo_Producto_ENTAsync(Entidades.Tipo_Producto pTipo_Producto) {
            return base.Channel.insTipo_Producto_ENTAsync(pTipo_Producto);
        }
        
        public bool modTipo_Producto_ENT(Entidades.Tipo_Producto pTipo_Producto) {
            return base.Channel.modTipo_Producto_ENT(pTipo_Producto);
        }
        
        public System.Threading.Tasks.Task<bool> modTipo_Producto_ENTAsync(Entidades.Tipo_Producto pTipo_Producto) {
            return base.Channel.modTipo_Producto_ENTAsync(pTipo_Producto);
        }
        
        public bool delTipo_Producto_ENT(Entidades.Tipo_Producto pTipo_Producto) {
            return base.Channel.delTipo_Producto_ENT(pTipo_Producto);
        }
        
        public System.Threading.Tasks.Task<bool> delTipo_Producto_ENTAsync(Entidades.Tipo_Producto pTipo_Producto) {
            return base.Channel.delTipo_Producto_ENTAsync(pTipo_Producto);
        }
        
        public System.Collections.Generic.List<Entidades.recTipo_Producto_Result> recTipo_Producto_PA() {
            return base.Channel.recTipo_Producto_PA();
        }
        
        public System.Threading.Tasks.Task<System.Collections.Generic.List<Entidades.recTipo_Producto_Result>> recTipo_Producto_PAAsync() {
            return base.Channel.recTipo_Producto_PAAsync();
        }
        
        public Entidades.recTipo_ProductoxId_Result recTipo_ProductoXId_PA(int pId) {
            return base.Channel.recTipo_ProductoXId_PA(pId);
        }
        
        public System.Threading.Tasks.Task<Entidades.recTipo_ProductoxId_Result> recTipo_ProductoXId_PAAsync(int pId) {
            return base.Channel.recTipo_ProductoXId_PAAsync(pId);
        }
        
        public bool insTipo_Producto_PA(Entidades.Tipo_Producto pTipo_Producto) {
            return base.Channel.insTipo_Producto_PA(pTipo_Producto);
        }
        
        public System.Threading.Tasks.Task<bool> insTipo_Producto_PAAsync(Entidades.Tipo_Producto pTipo_Producto) {
            return base.Channel.insTipo_Producto_PAAsync(pTipo_Producto);
        }
        
        public bool modTipo_Producto_PA(Entidades.Tipo_Producto pTipo_Producto) {
            return base.Channel.modTipo_Producto_PA(pTipo_Producto);
        }
        
        public System.Threading.Tasks.Task<bool> modTipo_Producto_PAAsync(Entidades.Tipo_Producto pTipo_Producto) {
            return base.Channel.modTipo_Producto_PAAsync(pTipo_Producto);
        }
        
        public bool delTipo_Producto_PA(Entidades.Tipo_Producto pTipo_Producto) {
            return base.Channel.delTipo_Producto_PA(pTipo_Producto);
        }
        
        public System.Threading.Tasks.Task<bool> delTipo_Producto_PAAsync(Entidades.Tipo_Producto pTipo_Producto) {
            return base.Channel.delTipo_Producto_PAAsync(pTipo_Producto);
        }
        
        public System.Collections.Generic.List<Entidades.recIngredientesXProducto_Result> recIngredienteXProducto_PA() {
            return base.Channel.recIngredienteXProducto_PA();
        }
        
        public System.Threading.Tasks.Task<System.Collections.Generic.List<Entidades.recIngredientesXProducto_Result>> recIngredienteXProducto_PAAsync() {
            return base.Channel.recIngredienteXProducto_PAAsync();
        }
        
        public Entidades.recIngredienteXProductoxId_Result recIngredienteXProductoXId_PA(int pId) {
            return base.Channel.recIngredienteXProductoXId_PA(pId);
        }
        
        public System.Threading.Tasks.Task<Entidades.recIngredienteXProductoxId_Result> recIngredienteXProductoXId_PAAsync(int pId) {
            return base.Channel.recIngredienteXProductoXId_PAAsync(pId);
        }
        
        public bool insIngredienteXProducto_PA(Entidades.Ingredientes_X_Producto pIngredienteXProducto) {
            return base.Channel.insIngredienteXProducto_PA(pIngredienteXProducto);
        }
        
        public System.Threading.Tasks.Task<bool> insIngredienteXProducto_PAAsync(Entidades.Ingredientes_X_Producto pIngredienteXProducto) {
            return base.Channel.insIngredienteXProducto_PAAsync(pIngredienteXProducto);
        }
        
        public bool modIngredienteXProducto_PA(Entidades.Ingredientes_X_Producto pIngredienteXProducto) {
            return base.Channel.modIngredienteXProducto_PA(pIngredienteXProducto);
        }
        
        public System.Threading.Tasks.Task<bool> modIngredienteXProducto_PAAsync(Entidades.Ingredientes_X_Producto pIngredienteXProducto) {
            return base.Channel.modIngredienteXProducto_PAAsync(pIngredienteXProducto);
        }
        
        public bool delIngredienteXProducto_PA(Entidades.Ingredientes_X_Producto pIngredienteXProducto) {
            return base.Channel.delIngredienteXProducto_PA(pIngredienteXProducto);
        }
        
        public System.Threading.Tasks.Task<bool> delIngredienteXProducto_PAAsync(Entidades.Ingredientes_X_Producto pIngredienteXProducto) {
            return base.Channel.delIngredienteXProducto_PAAsync(pIngredienteXProducto);
        }
        
        public System.Collections.Generic.List<Entidades.recEstados_Result> recEstado_PA() {
            return base.Channel.recEstado_PA();
        }
        
        public System.Threading.Tasks.Task<System.Collections.Generic.List<Entidades.recEstados_Result>> recEstado_PAAsync() {
            return base.Channel.recEstado_PAAsync();
        }
        
        public Entidades.recEstadoxId_Result recEstadoXId_PA(int pId) {
            return base.Channel.recEstadoXId_PA(pId);
        }
        
        public System.Threading.Tasks.Task<Entidades.recEstadoxId_Result> recEstadoXId_PAAsync(int pId) {
            return base.Channel.recEstadoXId_PAAsync(pId);
        }
        
        public bool insEstado_PA(Entidades.Estado pEstado) {
            return base.Channel.insEstado_PA(pEstado);
        }
        
        public System.Threading.Tasks.Task<bool> insEstado_PAAsync(Entidades.Estado pEstado) {
            return base.Channel.insEstado_PAAsync(pEstado);
        }
        
        public bool modEstado_PA(Entidades.Estado pEstado) {
            return base.Channel.modEstado_PA(pEstado);
        }
        
        public System.Threading.Tasks.Task<bool> modEstado_PAAsync(Entidades.Estado pEstado) {
            return base.Channel.modEstado_PAAsync(pEstado);
        }
        
        public bool delEstado_PA(Entidades.Estado pEstado) {
            return base.Channel.delEstado_PA(pEstado);
        }
        
        public System.Threading.Tasks.Task<bool> delEstado_PAAsync(Entidades.Estado pEstado) {
            return base.Channel.delEstado_PAAsync(pEstado);
        }
        
        public System.Collections.Generic.List<Entidades.recMesas_Result> recMesas_PA() {
            return base.Channel.recMesas_PA();
        }
        
        public System.Threading.Tasks.Task<System.Collections.Generic.List<Entidades.recMesas_Result>> recMesas_PAAsync() {
            return base.Channel.recMesas_PAAsync();
        }
        
        public Entidades.recMesaxId_Result recMesaXId_PA(int pId) {
            return base.Channel.recMesaXId_PA(pId);
        }
        
        public System.Threading.Tasks.Task<Entidades.recMesaxId_Result> recMesaXId_PAAsync(int pId) {
            return base.Channel.recMesaXId_PAAsync(pId);
        }
        
        public bool insMesas_PA(Entidades.Mesas pMesas) {
            return base.Channel.insMesas_PA(pMesas);
        }
        
        public System.Threading.Tasks.Task<bool> insMesas_PAAsync(Entidades.Mesas pMesas) {
            return base.Channel.insMesas_PAAsync(pMesas);
        }
        
        public bool modMesas_PA(Entidades.Mesas pMesas) {
            return base.Channel.modMesas_PA(pMesas);
        }
        
        public System.Threading.Tasks.Task<bool> modMesas_PAAsync(Entidades.Mesas pMesas) {
            return base.Channel.modMesas_PAAsync(pMesas);
        }
        
        public bool delMesas_PA(Entidades.Mesas pMesas) {
            return base.Channel.delMesas_PA(pMesas);
        }
        
        public System.Threading.Tasks.Task<bool> delMesas_PAAsync(Entidades.Mesas pMesas) {
            return base.Channel.delMesas_PAAsync(pMesas);
        }
        
        public System.Collections.Generic.List<Entidades.recOrdenes_Result> recOrdenes_PA() {
            return base.Channel.recOrdenes_PA();
        }
        
        public System.Threading.Tasks.Task<System.Collections.Generic.List<Entidades.recOrdenes_Result>> recOrdenes_PAAsync() {
            return base.Channel.recOrdenes_PAAsync();
        }
        
        public Entidades.recOrdenxId_Result recOrdenesXId_PA(int pId) {
            return base.Channel.recOrdenesXId_PA(pId);
        }
        
        public System.Threading.Tasks.Task<Entidades.recOrdenxId_Result> recOrdenesXId_PAAsync(int pId) {
            return base.Channel.recOrdenesXId_PAAsync(pId);
        }
        
        public bool insOrdenes_PAa(Entidades.Ordenes pOrdenes) {
            return base.Channel.insOrdenes_PAa(pOrdenes);
        }
        
        public System.Threading.Tasks.Task<bool> insOrdenes_PAaAsync(Entidades.Ordenes pOrdenes) {
            return base.Channel.insOrdenes_PAaAsync(pOrdenes);
        }
        
        public Entidades.ObtenerProductosPorCategoria_Result recObtenerProductosPorCategoria_ResultXId_PA(int pId) {
            return base.Channel.recObtenerProductosPorCategoria_ResultXId_PA(pId);
        }
        
        public System.Threading.Tasks.Task<Entidades.ObtenerProductosPorCategoria_Result> recObtenerProductosPorCategoria_ResultXId_PAAsync(int pId) {
            return base.Channel.recObtenerProductosPorCategoria_ResultXId_PAAsync(pId);
        }
        
        public Entidades.ObtenerOrdenesDeMesa_Result ObtenerOrdenesDeMesa_PA(int pId) {
            return base.Channel.ObtenerOrdenesDeMesa_PA(pId);
        }
        
        public System.Threading.Tasks.Task<Entidades.ObtenerOrdenesDeMesa_Result> ObtenerOrdenesDeMesa_PAAsync(int pId) {
            return base.Channel.ObtenerOrdenesDeMesa_PAAsync(pId);
        }
        
        public System.Collections.Generic.List<Entidades.Ordenes> recOrdenes_ENT() {
            return base.Channel.recOrdenes_ENT();
        }
        
        public System.Threading.Tasks.Task<System.Collections.Generic.List<Entidades.Ordenes>> recOrdenes_ENTAsync() {
            return base.Channel.recOrdenes_ENTAsync();
        }
        
        public Entidades.Ordenes recOrdenesXId_ENT(int pId) {
            return base.Channel.recOrdenesXId_ENT(pId);
        }
        
        public System.Threading.Tasks.Task<Entidades.Ordenes> recOrdenesXId_ENTAsync(int pId) {
            return base.Channel.recOrdenesXId_ENTAsync(pId);
        }
        
        public bool insOrdenes_ENT(Entidades.Ordenes pOrdenes) {
            return base.Channel.insOrdenes_ENT(pOrdenes);
        }
        
        public System.Threading.Tasks.Task<bool> insOrdenes_ENTAsync(Entidades.Ordenes pOrdenes) {
            return base.Channel.insOrdenes_ENTAsync(pOrdenes);
        }
        
        public bool modOrdenes_ENT(Entidades.Ordenes pOrdenes) {
            return base.Channel.modOrdenes_ENT(pOrdenes);
        }
        
        public System.Threading.Tasks.Task<bool> modOrdenes_ENTAsync(Entidades.Ordenes pOrdenes) {
            return base.Channel.modOrdenes_ENTAsync(pOrdenes);
        }
        
        public bool delOrdenes_ENT(Entidades.Ordenes pOrdenes) {
            return base.Channel.delOrdenes_ENT(pOrdenes);
        }
        
        public System.Threading.Tasks.Task<bool> delOrdenes_ENTAsync(Entidades.Ordenes pOrdenes) {
            return base.Channel.delOrdenes_ENTAsync(pOrdenes);
        }
        
        public System.Collections.Generic.List<Entidades.recDetalleOrden_Result> recDetalleOrden_PA() {
            return base.Channel.recDetalleOrden_PA();
        }
        
        public System.Threading.Tasks.Task<System.Collections.Generic.List<Entidades.recDetalleOrden_Result>> recDetalleOrden_PAAsync() {
            return base.Channel.recDetalleOrden_PAAsync();
        }
        
        public Entidades.recDetalleOrdenxId_Result recDetalleOrdenXId_PA(int pId) {
            return base.Channel.recDetalleOrdenXId_PA(pId);
        }
        
        public System.Threading.Tasks.Task<Entidades.recDetalleOrdenxId_Result> recDetalleOrdenXId_PAAsync(int pId) {
            return base.Channel.recDetalleOrdenXId_PAAsync(pId);
        }
        
        public bool insDetalleOrden_PA(Entidades.DetalleOrden pDetalleOrden) {
            return base.Channel.insDetalleOrden_PA(pDetalleOrden);
        }
        
        public System.Threading.Tasks.Task<bool> insDetalleOrden_PAAsync(Entidades.DetalleOrden pDetalleOrden) {
            return base.Channel.insDetalleOrden_PAAsync(pDetalleOrden);
        }
        
        public bool modDetalleOrden_PA(Entidades.DetalleOrden pDetalleOrden) {
            return base.Channel.modDetalleOrden_PA(pDetalleOrden);
        }
        
        public System.Threading.Tasks.Task<bool> modDetalleOrden_PAAsync(Entidades.DetalleOrden pDetalleOrden) {
            return base.Channel.modDetalleOrden_PAAsync(pDetalleOrden);
        }
        
        public bool delDetalleOrden_PA(Entidades.DetalleOrden pDetalleOrden) {
            return base.Channel.delDetalleOrden_PA(pDetalleOrden);
        }
        
        public System.Threading.Tasks.Task<bool> delDetalleOrden_PAAsync(Entidades.DetalleOrden pDetalleOrden) {
            return base.Channel.delDetalleOrden_PAAsync(pDetalleOrden);
        }
        
        public System.Collections.Generic.List<Entidades.DetalleOrden> recDetalleOrden_ENT() {
            return base.Channel.recDetalleOrden_ENT();
        }
        
        public System.Threading.Tasks.Task<System.Collections.Generic.List<Entidades.DetalleOrden>> recDetalleOrden_ENTAsync() {
            return base.Channel.recDetalleOrden_ENTAsync();
        }
        
        public Entidades.DetalleOrden recDetalleOrdenXId_ENT(int pId) {
            return base.Channel.recDetalleOrdenXId_ENT(pId);
        }
        
        public System.Threading.Tasks.Task<Entidades.DetalleOrden> recDetalleOrdenXId_ENTAsync(int pId) {
            return base.Channel.recDetalleOrdenXId_ENTAsync(pId);
        }
        
        public bool insDetalleOrden_ENT(Entidades.DetalleOrden pDetalleOrden) {
            return base.Channel.insDetalleOrden_ENT(pDetalleOrden);
        }
        
        public System.Threading.Tasks.Task<bool> insDetalleOrden_ENTAsync(Entidades.DetalleOrden pDetalleOrden) {
            return base.Channel.insDetalleOrden_ENTAsync(pDetalleOrden);
        }
        
        public bool modDetalleOrden_ENT(Entidades.DetalleOrden pDetalleOrden) {
            return base.Channel.modDetalleOrden_ENT(pDetalleOrden);
        }
        
        public System.Threading.Tasks.Task<bool> modDetalleOrden_ENTAsync(Entidades.DetalleOrden pDetalleOrden) {
            return base.Channel.modDetalleOrden_ENTAsync(pDetalleOrden);
        }
        
        public bool delDetalleOrden_ENT(Entidades.DetalleOrden pDetalleOrden) {
            return base.Channel.delDetalleOrden_ENT(pDetalleOrden);
        }
        
        public System.Threading.Tasks.Task<bool> delDetalleOrden_ENTAsync(Entidades.DetalleOrden pDetalleOrden) {
            return base.Channel.delDetalleOrden_ENTAsync(pDetalleOrden);
        }
        
        public System.Collections.Generic.List<Entidades.recPerfiles_Result> recPerfiles_PA() {
            return base.Channel.recPerfiles_PA();
        }
        
        public System.Threading.Tasks.Task<System.Collections.Generic.List<Entidades.recPerfiles_Result>> recPerfiles_PAAsync() {
            return base.Channel.recPerfiles_PAAsync();
        }
        
        public Entidades.recMesaPerfilxId_Result recPerfilesXId_PA(int pId) {
            return base.Channel.recPerfilesXId_PA(pId);
        }
        
        public System.Threading.Tasks.Task<Entidades.recMesaPerfilxId_Result> recPerfilesXId_PAAsync(int pId) {
            return base.Channel.recPerfilesXId_PAAsync(pId);
        }
        
        public bool insPerfiles_PA(Entidades.Perfiles pPerfiles) {
            return base.Channel.insPerfiles_PA(pPerfiles);
        }
        
        public System.Threading.Tasks.Task<bool> insPerfiles_PAAsync(Entidades.Perfiles pPerfiles) {
            return base.Channel.insPerfiles_PAAsync(pPerfiles);
        }
        
        public bool modPerfiles_PA(Entidades.Perfiles pPerfiles) {
            return base.Channel.modPerfiles_PA(pPerfiles);
        }
        
        public System.Threading.Tasks.Task<bool> modPerfiles_PAAsync(Entidades.Perfiles pPerfiles) {
            return base.Channel.modPerfiles_PAAsync(pPerfiles);
        }
        
        public bool delPerfiles_PA(Entidades.Perfiles pPerfiles) {
            return base.Channel.delPerfiles_PA(pPerfiles);
        }
        
        public System.Threading.Tasks.Task<bool> delPerfiles_PAAsync(Entidades.Perfiles pPerfiles) {
            return base.Channel.delPerfiles_PAAsync(pPerfiles);
        }
        
        public System.Collections.Generic.List<Entidades.recUsuarios_Result> recUsuarios_PA() {
            return base.Channel.recUsuarios_PA();
        }
        
        public System.Threading.Tasks.Task<System.Collections.Generic.List<Entidades.recUsuarios_Result>> recUsuarios_PAAsync() {
            return base.Channel.recUsuarios_PAAsync();
        }
        
        public Entidades.recUsuarioxId_Result recUsuariosXId_PA(string pId) {
            return base.Channel.recUsuariosXId_PA(pId);
        }
        
        public System.Threading.Tasks.Task<Entidades.recUsuarioxId_Result> recUsuariosXId_PAAsync(string pId) {
            return base.Channel.recUsuariosXId_PAAsync(pId);
        }
        
        public bool insUsuarios_PA(Entidades.Usuarios pUsuarios) {
            return base.Channel.insUsuarios_PA(pUsuarios);
        }
        
        public System.Threading.Tasks.Task<bool> insUsuarios_PAAsync(Entidades.Usuarios pUsuarios) {
            return base.Channel.insUsuarios_PAAsync(pUsuarios);
        }
        
        public bool modUsuarios_PA(Entidades.Usuarios pUsuarios) {
            return base.Channel.modUsuarios_PA(pUsuarios);
        }
        
        public System.Threading.Tasks.Task<bool> modUsuarios_PAAsync(Entidades.Usuarios pUsuarios) {
            return base.Channel.modUsuarios_PAAsync(pUsuarios);
        }
        
        public bool delUsuarios_PA(Entidades.Usuarios pUsuarios) {
            return base.Channel.delUsuarios_PA(pUsuarios);
        }
        
        public System.Threading.Tasks.Task<bool> delUsuarios_PAAsync(Entidades.Usuarios pUsuarios) {
            return base.Channel.delUsuarios_PAAsync(pUsuarios);
        }
        
        public System.Collections.Generic.List<Entidades.recPerfilUsuario_Result> recPerfilUsuario_PA() {
            return base.Channel.recPerfilUsuario_PA();
        }
        
        public System.Threading.Tasks.Task<System.Collections.Generic.List<Entidades.recPerfilUsuario_Result>> recPerfilUsuario_PAAsync() {
            return base.Channel.recPerfilUsuario_PAAsync();
        }
        
        public Entidades.recPerfilUsuarioxId_Result recPerfilUsuarioXId_PA(int pId) {
            return base.Channel.recPerfilUsuarioXId_PA(pId);
        }
        
        public System.Threading.Tasks.Task<Entidades.recPerfilUsuarioxId_Result> recPerfilUsuarioXId_PAAsync(int pId) {
            return base.Channel.recPerfilUsuarioXId_PAAsync(pId);
        }
        
        public bool insPerfilUsuario_PA(Entidades.PerfilUsuario pPerfilUsuario) {
            return base.Channel.insPerfilUsuario_PA(pPerfilUsuario);
        }
        
        public System.Threading.Tasks.Task<bool> insPerfilUsuario_PAAsync(Entidades.PerfilUsuario pPerfilUsuario) {
            return base.Channel.insPerfilUsuario_PAAsync(pPerfilUsuario);
        }
        
        public bool modPerfilUsuario_PA(Entidades.PerfilUsuario pPerfilUsuario) {
            return base.Channel.modPerfilUsuario_PA(pPerfilUsuario);
        }
        
        public System.Threading.Tasks.Task<bool> modPerfilUsuario_PAAsync(Entidades.PerfilUsuario pPerfilUsuario) {
            return base.Channel.modPerfilUsuario_PAAsync(pPerfilUsuario);
        }
        
        public bool delPerfilUsuario_PA(Entidades.PerfilUsuario pPerfilUsuario) {
            return base.Channel.delPerfilUsuario_PA(pPerfilUsuario);
        }
        
        public System.Threading.Tasks.Task<bool> delPerfilUsuario_PAAsync(Entidades.PerfilUsuario pPerfilUsuario) {
            return base.Channel.delPerfilUsuario_PAAsync(pPerfilUsuario);
        }
    }
}
