//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Entidades
{
    using System;
    using System.Collections.Generic;
    
    public partial class Ingredientes_X_Producto
    {
        public int Id_ingredienteXproducto { get; set; }
        public int Id_producto { get; set; }
        public Nullable<int> Id_Ingrediente { get; set; }
    
        public virtual Ingredientes Ingredientes { get; set; }
        public virtual Productos Productos { get; set; }
    }
}
