//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MVCMuncheese.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tipo_Producto
    {
        public int Id_tipo_Producto { get; set; }
        public string Nombre_tipo_pro { get; set; }
    }
}
