//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AccesoDatos
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    using Entidades;
    public partial class MuncheeseEntidades : DbContext
    {
        public MuncheeseEntidades()
            : base("name=MuncheeseEntidades")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Clientes> Clientes { get; set; }
        public virtual DbSet<DetalleOrden> DetalleOrden { get; set; }
        public virtual DbSet<Estado> Estado { get; set; }
        public virtual DbSet<Facturas> Facturas { get; set; }
        public virtual DbSet<Ingredientes> Ingredientes { get; set; }
        public virtual DbSet<Ingredientes_X_Producto> Ingredientes_X_Producto { get; set; }
        public virtual DbSet<Inventario> Inventario { get; set; }
        public virtual DbSet<Mesas> Mesas { get; set; }
        public virtual DbSet<Ordenes> Ordenes { get; set; }
        public virtual DbSet<Perfiles> Perfiles { get; set; }
        public virtual DbSet<PerfilUsuario> PerfilUsuario { get; set; }
        public virtual DbSet<Productos> Productos { get; set; }
        public virtual DbSet<Proveedor> Proveedor { get; set; }
        public virtual DbSet<sysdiagrams> sysdiagrams { get; set; }
        public virtual DbSet<Tipo_Producto> Tipo_Producto { get; set; }
        public virtual DbSet<Usuarios> Usuarios { get; set; }
    
        public virtual int DELCliente(string telefono)
        {
            var telefonoParameter = telefono != null ?
                new ObjectParameter("Telefono", telefono) :
                new ObjectParameter("Telefono", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("DELCliente", telefonoParameter);
        }
    
        public virtual int delCombo(Nullable<int> id_combo)
        {
            var id_comboParameter = id_combo.HasValue ?
                new ObjectParameter("Id_combo", id_combo) :
                new ObjectParameter("Id_combo", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("delCombo", id_comboParameter);
        }
    
        public virtual int delDetalleOrden(Nullable<int> id_Detalle)
        {
            var id_DetalleParameter = id_Detalle.HasValue ?
                new ObjectParameter("Id_Detalle", id_Detalle) :
                new ObjectParameter("Id_Detalle", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("delDetalleOrden", id_DetalleParameter);
        }
    
        public virtual int delEstado(Nullable<int> id_Estado)
        {
            var id_EstadoParameter = id_Estado.HasValue ?
                new ObjectParameter("Id_Estado", id_Estado) :
                new ObjectParameter("Id_Estado", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("delEstado", id_EstadoParameter);
        }
    
        public virtual int delFactura(Nullable<int> id_Factura)
        {
            var id_FacturaParameter = id_Factura.HasValue ?
                new ObjectParameter("Id_Factura", id_Factura) :
                new ObjectParameter("Id_Factura", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("delFactura", id_FacturaParameter);
        }
    
        public virtual int delIngrediente(Nullable<int> id_Ingrediente)
        {
            var id_IngredienteParameter = id_Ingrediente.HasValue ?
                new ObjectParameter("Id_Ingrediente", id_Ingrediente) :
                new ObjectParameter("Id_Ingrediente", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("delIngrediente", id_IngredienteParameter);
        }
    
        public virtual int delIngredienteXproducto(Nullable<int> id_IngredienteXproducto)
        {
            var id_IngredienteXproductoParameter = id_IngredienteXproducto.HasValue ?
                new ObjectParameter("Id_IngredienteXproducto", id_IngredienteXproducto) :
                new ObjectParameter("Id_IngredienteXproducto", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("delIngredienteXproducto", id_IngredienteXproductoParameter);
        }
    
        public virtual int delInventario(Nullable<int> id_inventario)
        {
            var id_inventarioParameter = id_inventario.HasValue ?
                new ObjectParameter("Id_inventario", id_inventario) :
                new ObjectParameter("Id_inventario", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("delInventario", id_inventarioParameter);
        }
    
        public virtual int delMesa(Nullable<int> id_Mesa)
        {
            var id_MesaParameter = id_Mesa.HasValue ?
                new ObjectParameter("Id_Mesa", id_Mesa) :
                new ObjectParameter("Id_Mesa", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("delMesa", id_MesaParameter);
        }
    
        public virtual int delOrden(Nullable<int> id_Orden)
        {
            var id_OrdenParameter = id_Orden.HasValue ?
                new ObjectParameter("Id_Orden", id_Orden) :
                new ObjectParameter("Id_Orden", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("delOrden", id_OrdenParameter);
        }
    
        public virtual int delPerfil(Nullable<int> perfil_Id)
        {
            var perfil_IdParameter = perfil_Id.HasValue ?
                new ObjectParameter("Perfil_Id", perfil_Id) :
                new ObjectParameter("Perfil_Id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("delPerfil", perfil_IdParameter);
        }
    
        public virtual int delPerfilUsuario(Nullable<int> id_PerfilUsuario)
        {
            var id_PerfilUsuarioParameter = id_PerfilUsuario.HasValue ?
                new ObjectParameter("Id_PerfilUsuario", id_PerfilUsuario) :
                new ObjectParameter("Id_PerfilUsuario", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("delPerfilUsuario", id_PerfilUsuarioParameter);
        }
    
        public virtual int delproducto(Nullable<int> id_producto)
        {
            var id_productoParameter = id_producto.HasValue ?
                new ObjectParameter("Id_producto", id_producto) :
                new ObjectParameter("Id_producto", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("delproducto", id_productoParameter);
        }
    
        public virtual int delProductosXcombo(Nullable<int> id_ProducXcombo)
        {
            var id_ProducXcomboParameter = id_ProducXcombo.HasValue ?
                new ObjectParameter("Id_ProducXcombo", id_ProducXcombo) :
                new ObjectParameter("Id_ProducXcombo", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("delProductosXcombo", id_ProducXcomboParameter);
        }
    
        public virtual int DELProveedor(Nullable<int> idProveedor)
        {
            var idProveedorParameter = idProveedor.HasValue ?
                new ObjectParameter("IdProveedor", idProveedor) :
                new ObjectParameter("IdProveedor", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("DELProveedor", idProveedorParameter);
        }
    
        public virtual int delTipo_Combo(Nullable<int> id_tipo_combo)
        {
            var id_tipo_comboParameter = id_tipo_combo.HasValue ?
                new ObjectParameter("Id_tipo_combo", id_tipo_combo) :
                new ObjectParameter("Id_tipo_combo", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("delTipo_Combo", id_tipo_comboParameter);
        }
    
        public virtual int delTipo_Producto(Nullable<int> id_tipo_Producto)
        {
            var id_tipo_ProductoParameter = id_tipo_Producto.HasValue ?
                new ObjectParameter("Id_tipo_Producto", id_tipo_Producto) :
                new ObjectParameter("Id_tipo_Producto", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("delTipo_Producto", id_tipo_ProductoParameter);
        }
    
        public virtual int delUsuario(string usuario)
        {
            var usuarioParameter = usuario != null ?
                new ObjectParameter("Usuario", usuario) :
                new ObjectParameter("Usuario", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("delUsuario", usuarioParameter);
        }
    
        public virtual int insCliente(string telefono, string nombre, string apellido_1, string apellido_2, string direccion)
        {
            var telefonoParameter = telefono != null ?
                new ObjectParameter("Telefono", telefono) :
                new ObjectParameter("Telefono", typeof(string));
    
            var nombreParameter = nombre != null ?
                new ObjectParameter("Nombre", nombre) :
                new ObjectParameter("Nombre", typeof(string));
    
            var apellido_1Parameter = apellido_1 != null ?
                new ObjectParameter("Apellido_1", apellido_1) :
                new ObjectParameter("Apellido_1", typeof(string));
    
            var apellido_2Parameter = apellido_2 != null ?
                new ObjectParameter("Apellido_2", apellido_2) :
                new ObjectParameter("Apellido_2", typeof(string));
    
            var direccionParameter = direccion != null ?
                new ObjectParameter("Direccion", direccion) :
                new ObjectParameter("Direccion", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("insCliente", telefonoParameter, nombreParameter, apellido_1Parameter, apellido_2Parameter, direccionParameter);
        }
    
        public virtual int insCombo(Nullable<int> id_combo, string nombre, Nullable<int> tipo_combo, Nullable<int> precio, string descripcion)
        {
            var id_comboParameter = id_combo.HasValue ?
                new ObjectParameter("Id_combo", id_combo) :
                new ObjectParameter("Id_combo", typeof(int));
    
            var nombreParameter = nombre != null ?
                new ObjectParameter("Nombre", nombre) :
                new ObjectParameter("Nombre", typeof(string));
    
            var tipo_comboParameter = tipo_combo.HasValue ?
                new ObjectParameter("Tipo_combo", tipo_combo) :
                new ObjectParameter("Tipo_combo", typeof(int));
    
            var precioParameter = precio.HasValue ?
                new ObjectParameter("Precio", precio) :
                new ObjectParameter("Precio", typeof(int));
    
            var descripcionParameter = descripcion != null ?
                new ObjectParameter("Descripcion", descripcion) :
                new ObjectParameter("Descripcion", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("insCombo", id_comboParameter, nombreParameter, tipo_comboParameter, precioParameter, descripcionParameter);
        }
    
        public virtual int insDetalleOrden(Nullable<int> id_Orden, Nullable<int> id_producto, Nullable<int> cantidad, Nullable<int> mesa, Nullable<int> precio, string tipo_orden, string descripcion)
        {
            var id_OrdenParameter = id_Orden.HasValue ?
                new ObjectParameter("Id_Orden", id_Orden) :
                new ObjectParameter("Id_Orden", typeof(int));
    
            var id_productoParameter = id_producto.HasValue ?
                new ObjectParameter("Id_producto", id_producto) :
                new ObjectParameter("Id_producto", typeof(int));
    
            var cantidadParameter = cantidad.HasValue ?
                new ObjectParameter("Cantidad", cantidad) :
                new ObjectParameter("Cantidad", typeof(int));
    
            var mesaParameter = mesa.HasValue ?
                new ObjectParameter("Mesa", mesa) :
                new ObjectParameter("Mesa", typeof(int));
    
            var precioParameter = precio.HasValue ?
                new ObjectParameter("Precio", precio) :
                new ObjectParameter("Precio", typeof(int));
    
            var tipo_ordenParameter = tipo_orden != null ?
                new ObjectParameter("Tipo_orden", tipo_orden) :
                new ObjectParameter("Tipo_orden", typeof(string));
    
            var descripcionParameter = descripcion != null ?
                new ObjectParameter("Descripcion", descripcion) :
                new ObjectParameter("Descripcion", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("insDetalleOrden", id_OrdenParameter, id_productoParameter, cantidadParameter, mesaParameter, precioParameter, tipo_ordenParameter, descripcionParameter);
        }
    
        public virtual ObjectResult<InsertarTipoProducto_Result> InsertarTipoProducto(string nombre_tipo_pro)
        {
            var nombre_tipo_proParameter = nombre_tipo_pro != null ?
                new ObjectParameter("Nombre_tipo_pro", nombre_tipo_pro) :
                new ObjectParameter("Nombre_tipo_pro", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<InsertarTipoProducto_Result>("InsertarTipoProducto", nombre_tipo_proParameter);
        }
    
        public virtual int insertProducto(string nombre, Nullable<int> tipo_producto, Nullable<int> precio, string descripcion)
        {
            var nombreParameter = nombre != null ?
                new ObjectParameter("Nombre", nombre) :
                new ObjectParameter("Nombre", typeof(string));
    
            var tipo_productoParameter = tipo_producto.HasValue ?
                new ObjectParameter("Tipo_producto", tipo_producto) :
                new ObjectParameter("Tipo_producto", typeof(int));
    
            var precioParameter = precio.HasValue ?
                new ObjectParameter("Precio", precio) :
                new ObjectParameter("Precio", typeof(int));
    
            var descripcionParameter = descripcion != null ?
                new ObjectParameter("Descripcion", descripcion) :
                new ObjectParameter("Descripcion", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("insertProducto", nombreParameter, tipo_productoParameter, precioParameter, descripcionParameter);
        }
    
        public virtual int insEstado(string estado)
        {
            var estadoParameter = estado != null ?
                new ObjectParameter("Estado", estado) :
                new ObjectParameter("Estado", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("insEstado", estadoParameter);
        }
    
        public virtual int insFactura(Nullable<System.DateTime> fecha, Nullable<int> id_Orden, string tel_Cliente)
        {
            var fechaParameter = fecha.HasValue ?
                new ObjectParameter("fecha", fecha) :
                new ObjectParameter("fecha", typeof(System.DateTime));
    
            var id_OrdenParameter = id_Orden.HasValue ?
                new ObjectParameter("Id_Orden", id_Orden) :
                new ObjectParameter("Id_Orden", typeof(int));
    
            var tel_ClienteParameter = tel_Cliente != null ?
                new ObjectParameter("Tel_Cliente", tel_Cliente) :
                new ObjectParameter("Tel_Cliente", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("insFactura", fechaParameter, id_OrdenParameter, tel_ClienteParameter);
        }
    
        public virtual int insIngrediente(Nullable<int> id_Ingrediente, string nombre_Ingrediente)
        {
            var id_IngredienteParameter = id_Ingrediente.HasValue ?
                new ObjectParameter("Id_Ingrediente", id_Ingrediente) :
                new ObjectParameter("Id_Ingrediente", typeof(int));
    
            var nombre_IngredienteParameter = nombre_Ingrediente != null ?
                new ObjectParameter("Nombre_Ingrediente", nombre_Ingrediente) :
                new ObjectParameter("Nombre_Ingrediente", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("insIngrediente", id_IngredienteParameter, nombre_IngredienteParameter);
        }
    
        public virtual int insIngredienteXProducto(Nullable<int> id_IngredienteXproducto, Nullable<int> id_producto, Nullable<int> id_Ingrediente)
        {
            var id_IngredienteXproductoParameter = id_IngredienteXproducto.HasValue ?
                new ObjectParameter("Id_IngredienteXproducto", id_IngredienteXproducto) :
                new ObjectParameter("Id_IngredienteXproducto", typeof(int));
    
            var id_productoParameter = id_producto.HasValue ?
                new ObjectParameter("Id_producto", id_producto) :
                new ObjectParameter("Id_producto", typeof(int));
    
            var id_IngredienteParameter = id_Ingrediente.HasValue ?
                new ObjectParameter("Id_Ingrediente", id_Ingrediente) :
                new ObjectParameter("Id_Ingrediente", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("insIngredienteXProducto", id_IngredienteXproductoParameter, id_productoParameter, id_IngredienteParameter);
        }
    
        public virtual int insInventario(string nombre_Producto, Nullable<int> cantidad, Nullable<int> id_Producto)
        {
            var nombre_ProductoParameter = nombre_Producto != null ?
                new ObjectParameter("Nombre_Producto", nombre_Producto) :
                new ObjectParameter("Nombre_Producto", typeof(string));
    
            var cantidadParameter = cantidad.HasValue ?
                new ObjectParameter("Cantidad", cantidad) :
                new ObjectParameter("Cantidad", typeof(int));
    
            var id_ProductoParameter = id_Producto.HasValue ?
                new ObjectParameter("Id_Producto", id_Producto) :
                new ObjectParameter("Id_Producto", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("insInventario", nombre_ProductoParameter, cantidadParameter, id_ProductoParameter);
        }
    
        public virtual int insMesa(string nombreMesa, Nullable<int> estado)
        {
            var nombreMesaParameter = nombreMesa != null ?
                new ObjectParameter("NombreMesa", nombreMesa) :
                new ObjectParameter("NombreMesa", typeof(string));
    
            var estadoParameter = estado.HasValue ?
                new ObjectParameter("Estado", estado) :
                new ObjectParameter("Estado", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("insMesa", nombreMesaParameter, estadoParameter);
        }
    
        public virtual int insOrden()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("insOrden");
        }
    
        public virtual int insPerfil(string nombre_perfil)
        {
            var nombre_perfilParameter = nombre_perfil != null ?
                new ObjectParameter("nombre_perfil", nombre_perfil) :
                new ObjectParameter("nombre_perfil", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("insPerfil", nombre_perfilParameter);
        }
    
        public virtual int insPerfilUsuario(Nullable<int> perfil_id, string usuario)
        {
            var perfil_idParameter = perfil_id.HasValue ?
                new ObjectParameter("Perfil_id", perfil_id) :
                new ObjectParameter("Perfil_id", typeof(int));
    
            var usuarioParameter = usuario != null ?
                new ObjectParameter("Usuario", usuario) :
                new ObjectParameter("Usuario", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("insPerfilUsuario", perfil_idParameter, usuarioParameter);
        }
    
        public virtual int insProducto(Nullable<int> id_producto, string nombre, Nullable<int> tipo_producto, Nullable<int> precio, string descripcion)
        {
            var id_productoParameter = id_producto.HasValue ?
                new ObjectParameter("Id_producto", id_producto) :
                new ObjectParameter("Id_producto", typeof(int));
    
            var nombreParameter = nombre != null ?
                new ObjectParameter("Nombre", nombre) :
                new ObjectParameter("Nombre", typeof(string));
    
            var tipo_productoParameter = tipo_producto.HasValue ?
                new ObjectParameter("Tipo_producto", tipo_producto) :
                new ObjectParameter("Tipo_producto", typeof(int));
    
            var precioParameter = precio.HasValue ?
                new ObjectParameter("Precio", precio) :
                new ObjectParameter("Precio", typeof(int));
    
            var descripcionParameter = descripcion != null ?
                new ObjectParameter("Descripcion", descripcion) :
                new ObjectParameter("Descripcion", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("insProducto", id_productoParameter, nombreParameter, tipo_productoParameter, precioParameter, descripcionParameter);
        }
    
        public virtual int insProductosXcombo(Nullable<int> id_combo, Nullable<int> id_producto)
        {
            var id_comboParameter = id_combo.HasValue ?
                new ObjectParameter("Id_combo", id_combo) :
                new ObjectParameter("Id_combo", typeof(int));
    
            var id_productoParameter = id_producto.HasValue ?
                new ObjectParameter("Id_producto", id_producto) :
                new ObjectParameter("Id_producto", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("insProductosXcombo", id_comboParameter, id_productoParameter);
        }
    
        public virtual int insProveedor(Nullable<int> idProveedor, string nombre, string apellido_1, string apellido_2, string telefono, string producto)
        {
            var idProveedorParameter = idProveedor.HasValue ?
                new ObjectParameter("IdProveedor", idProveedor) :
                new ObjectParameter("IdProveedor", typeof(int));
    
            var nombreParameter = nombre != null ?
                new ObjectParameter("Nombre", nombre) :
                new ObjectParameter("Nombre", typeof(string));
    
            var apellido_1Parameter = apellido_1 != null ?
                new ObjectParameter("Apellido_1", apellido_1) :
                new ObjectParameter("Apellido_1", typeof(string));
    
            var apellido_2Parameter = apellido_2 != null ?
                new ObjectParameter("Apellido_2", apellido_2) :
                new ObjectParameter("Apellido_2", typeof(string));
    
            var telefonoParameter = telefono != null ?
                new ObjectParameter("Telefono", telefono) :
                new ObjectParameter("Telefono", typeof(string));
    
            var productoParameter = producto != null ?
                new ObjectParameter("Producto", producto) :
                new ObjectParameter("Producto", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("insProveedor", idProveedorParameter, nombreParameter, apellido_1Parameter, apellido_2Parameter, telefonoParameter, productoParameter);
        }
    
        public virtual int insTipo_Combo(Nullable<int> id_tipo_combo, string nombre_tipo_com)
        {
            var id_tipo_comboParameter = id_tipo_combo.HasValue ?
                new ObjectParameter("Id_tipo_combo", id_tipo_combo) :
                new ObjectParameter("Id_tipo_combo", typeof(int));
    
            var nombre_tipo_comParameter = nombre_tipo_com != null ?
                new ObjectParameter("Nombre_tipo_com", nombre_tipo_com) :
                new ObjectParameter("Nombre_tipo_com", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("insTipo_Combo", id_tipo_comboParameter, nombre_tipo_comParameter);
        }
    
        public virtual int insTipo_Producto(Nullable<int> id_tipo_Producto, string nombre_tipo_pro)
        {
            var id_tipo_ProductoParameter = id_tipo_Producto.HasValue ?
                new ObjectParameter("Id_tipo_Producto", id_tipo_Producto) :
                new ObjectParameter("Id_tipo_Producto", typeof(int));
    
            var nombre_tipo_proParameter = nombre_tipo_pro != null ?
                new ObjectParameter("Nombre_tipo_pro", nombre_tipo_pro) :
                new ObjectParameter("Nombre_tipo_pro", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("insTipo_Producto", id_tipo_ProductoParameter, nombre_tipo_proParameter);
        }
    
        public virtual int insUsuario(string usuario, string contraseña, Nullable<int> estado)
        {
            var usuarioParameter = usuario != null ?
                new ObjectParameter("Usuario", usuario) :
                new ObjectParameter("Usuario", typeof(string));
    
            var contraseñaParameter = contraseña != null ?
                new ObjectParameter("Contraseña", contraseña) :
                new ObjectParameter("Contraseña", typeof(string));
    
            var estadoParameter = estado.HasValue ?
                new ObjectParameter("Estado", estado) :
                new ObjectParameter("Estado", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("insUsuario", usuarioParameter, contraseñaParameter, estadoParameter);
        }
    
        public virtual int modCliente(string telefono, string nombre, string apellido_1, string apellido_2, string direccion)
        {
            var telefonoParameter = telefono != null ?
                new ObjectParameter("Telefono", telefono) :
                new ObjectParameter("Telefono", typeof(string));
    
            var nombreParameter = nombre != null ?
                new ObjectParameter("Nombre", nombre) :
                new ObjectParameter("Nombre", typeof(string));
    
            var apellido_1Parameter = apellido_1 != null ?
                new ObjectParameter("Apellido_1", apellido_1) :
                new ObjectParameter("Apellido_1", typeof(string));
    
            var apellido_2Parameter = apellido_2 != null ?
                new ObjectParameter("Apellido_2", apellido_2) :
                new ObjectParameter("Apellido_2", typeof(string));
    
            var direccionParameter = direccion != null ?
                new ObjectParameter("Direccion", direccion) :
                new ObjectParameter("Direccion", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("modCliente", telefonoParameter, nombreParameter, apellido_1Parameter, apellido_2Parameter, direccionParameter);
        }
    
        public virtual int modCombos(Nullable<int> id_combo, string nombre, Nullable<int> tipo_combo, Nullable<int> precio, string descripcion)
        {
            var id_comboParameter = id_combo.HasValue ?
                new ObjectParameter("Id_combo", id_combo) :
                new ObjectParameter("Id_combo", typeof(int));
    
            var nombreParameter = nombre != null ?
                new ObjectParameter("Nombre", nombre) :
                new ObjectParameter("Nombre", typeof(string));
    
            var tipo_comboParameter = tipo_combo.HasValue ?
                new ObjectParameter("Tipo_combo", tipo_combo) :
                new ObjectParameter("Tipo_combo", typeof(int));
    
            var precioParameter = precio.HasValue ?
                new ObjectParameter("Precio", precio) :
                new ObjectParameter("Precio", typeof(int));
    
            var descripcionParameter = descripcion != null ?
                new ObjectParameter("Descripcion", descripcion) :
                new ObjectParameter("Descripcion", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("modCombos", id_comboParameter, nombreParameter, tipo_comboParameter, precioParameter, descripcionParameter);
        }
    
        public virtual int modDetalleOrden(Nullable<int> id_Detalle, Nullable<int> id_Orden, Nullable<int> id_producto, Nullable<int> cantidad, Nullable<int> mesa, Nullable<int> precio, string tipo_orden, string descripcion)
        {
            var id_DetalleParameter = id_Detalle.HasValue ?
                new ObjectParameter("Id_Detalle", id_Detalle) :
                new ObjectParameter("Id_Detalle", typeof(int));
    
            var id_OrdenParameter = id_Orden.HasValue ?
                new ObjectParameter("Id_Orden", id_Orden) :
                new ObjectParameter("Id_Orden", typeof(int));
    
            var id_productoParameter = id_producto.HasValue ?
                new ObjectParameter("Id_producto", id_producto) :
                new ObjectParameter("Id_producto", typeof(int));
    
            var cantidadParameter = cantidad.HasValue ?
                new ObjectParameter("Cantidad", cantidad) :
                new ObjectParameter("Cantidad", typeof(int));
    
            var mesaParameter = mesa.HasValue ?
                new ObjectParameter("Mesa", mesa) :
                new ObjectParameter("Mesa", typeof(int));
    
            var precioParameter = precio.HasValue ?
                new ObjectParameter("Precio", precio) :
                new ObjectParameter("Precio", typeof(int));
    
            var tipo_ordenParameter = tipo_orden != null ?
                new ObjectParameter("Tipo_orden", tipo_orden) :
                new ObjectParameter("Tipo_orden", typeof(string));
    
            var descripcionParameter = descripcion != null ?
                new ObjectParameter("Descripcion", descripcion) :
                new ObjectParameter("Descripcion", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("modDetalleOrden", id_DetalleParameter, id_OrdenParameter, id_productoParameter, cantidadParameter, mesaParameter, precioParameter, tipo_ordenParameter, descripcionParameter);
        }
    
        public virtual int modEstado(Nullable<int> id_Estado, string estado)
        {
            var id_EstadoParameter = id_Estado.HasValue ?
                new ObjectParameter("Id_Estado", id_Estado) :
                new ObjectParameter("Id_Estado", typeof(int));
    
            var estadoParameter = estado != null ?
                new ObjectParameter("Estado", estado) :
                new ObjectParameter("Estado", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("modEstado", id_EstadoParameter, estadoParameter);
        }
    
        public virtual int modFactura(Nullable<int> id_Factura, Nullable<System.DateTime> fecha, Nullable<int> id_Orden, string tel_Cliente)
        {
            var id_FacturaParameter = id_Factura.HasValue ?
                new ObjectParameter("Id_Factura", id_Factura) :
                new ObjectParameter("Id_Factura", typeof(int));
    
            var fechaParameter = fecha.HasValue ?
                new ObjectParameter("fecha", fecha) :
                new ObjectParameter("fecha", typeof(System.DateTime));
    
            var id_OrdenParameter = id_Orden.HasValue ?
                new ObjectParameter("Id_Orden", id_Orden) :
                new ObjectParameter("Id_Orden", typeof(int));
    
            var tel_ClienteParameter = tel_Cliente != null ?
                new ObjectParameter("Tel_Cliente", tel_Cliente) :
                new ObjectParameter("Tel_Cliente", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("modFactura", id_FacturaParameter, fechaParameter, id_OrdenParameter, tel_ClienteParameter);
        }
    
        public virtual int modIngrediente(Nullable<int> id_Ingrediente, string nombre_Ingrediente)
        {
            var id_IngredienteParameter = id_Ingrediente.HasValue ?
                new ObjectParameter("Id_Ingrediente", id_Ingrediente) :
                new ObjectParameter("Id_Ingrediente", typeof(int));
    
            var nombre_IngredienteParameter = nombre_Ingrediente != null ?
                new ObjectParameter("Nombre_Ingrediente", nombre_Ingrediente) :
                new ObjectParameter("Nombre_Ingrediente", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("modIngrediente", id_IngredienteParameter, nombre_IngredienteParameter);
        }
    
        public virtual int modIngredientesXProducto(Nullable<int> id_IngredienteXproducto, Nullable<int> id_producto, Nullable<int> id_Ingrediente)
        {
            var id_IngredienteXproductoParameter = id_IngredienteXproducto.HasValue ?
                new ObjectParameter("Id_IngredienteXproducto", id_IngredienteXproducto) :
                new ObjectParameter("Id_IngredienteXproducto", typeof(int));
    
            var id_productoParameter = id_producto.HasValue ?
                new ObjectParameter("Id_producto", id_producto) :
                new ObjectParameter("Id_producto", typeof(int));
    
            var id_IngredienteParameter = id_Ingrediente.HasValue ?
                new ObjectParameter("Id_Ingrediente", id_Ingrediente) :
                new ObjectParameter("Id_Ingrediente", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("modIngredientesXProducto", id_IngredienteXproductoParameter, id_productoParameter, id_IngredienteParameter);
        }
    
        public virtual int modInventario(Nullable<int> id_inventario, string nombre_Producto, Nullable<int> cantidad, Nullable<int> id_Producto)
        {
            var id_inventarioParameter = id_inventario.HasValue ?
                new ObjectParameter("Id_inventario", id_inventario) :
                new ObjectParameter("Id_inventario", typeof(int));
    
            var nombre_ProductoParameter = nombre_Producto != null ?
                new ObjectParameter("Nombre_Producto", nombre_Producto) :
                new ObjectParameter("Nombre_Producto", typeof(string));
    
            var cantidadParameter = cantidad.HasValue ?
                new ObjectParameter("Cantidad", cantidad) :
                new ObjectParameter("Cantidad", typeof(int));
    
            var id_ProductoParameter = id_Producto.HasValue ?
                new ObjectParameter("Id_Producto", id_Producto) :
                new ObjectParameter("Id_Producto", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("modInventario", id_inventarioParameter, nombre_ProductoParameter, cantidadParameter, id_ProductoParameter);
        }
    
        public virtual int modMesa(Nullable<int> id_Mesa, string nombreMesa, Nullable<int> estado)
        {
            var id_MesaParameter = id_Mesa.HasValue ?
                new ObjectParameter("Id_Mesa", id_Mesa) :
                new ObjectParameter("Id_Mesa", typeof(int));
    
            var nombreMesaParameter = nombreMesa != null ?
                new ObjectParameter("NombreMesa", nombreMesa) :
                new ObjectParameter("NombreMesa", typeof(string));
    
            var estadoParameter = estado.HasValue ?
                new ObjectParameter("Estado", estado) :
                new ObjectParameter("Estado", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("modMesa", id_MesaParameter, nombreMesaParameter, estadoParameter);
        }
    
        public virtual int modOrdenes(Nullable<int> id_Orden, Nullable<System.DateTime> fecha, Nullable<int> estado)
        {
            var id_OrdenParameter = id_Orden.HasValue ?
                new ObjectParameter("Id_Orden", id_Orden) :
                new ObjectParameter("Id_Orden", typeof(int));
    
            var fechaParameter = fecha.HasValue ?
                new ObjectParameter("Fecha", fecha) :
                new ObjectParameter("Fecha", typeof(System.DateTime));
    
            var estadoParameter = estado.HasValue ?
                new ObjectParameter("Estado", estado) :
                new ObjectParameter("Estado", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("modOrdenes", id_OrdenParameter, fechaParameter, estadoParameter);
        }
    
        public virtual int modPerfil(Nullable<int> perfil_Id, string nombre_perfil)
        {
            var perfil_IdParameter = perfil_Id.HasValue ?
                new ObjectParameter("Perfil_Id", perfil_Id) :
                new ObjectParameter("Perfil_Id", typeof(int));
    
            var nombre_perfilParameter = nombre_perfil != null ?
                new ObjectParameter("nombre_perfil", nombre_perfil) :
                new ObjectParameter("nombre_perfil", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("modPerfil", perfil_IdParameter, nombre_perfilParameter);
        }
    
        public virtual int modPerfilUsuario(Nullable<int> perfil_Id, string usuario, Nullable<int> id_PerfilUsuario)
        {
            var perfil_IdParameter = perfil_Id.HasValue ?
                new ObjectParameter("Perfil_Id", perfil_Id) :
                new ObjectParameter("Perfil_Id", typeof(int));
    
            var usuarioParameter = usuario != null ?
                new ObjectParameter("Usuario", usuario) :
                new ObjectParameter("Usuario", typeof(string));
    
            var id_PerfilUsuarioParameter = id_PerfilUsuario.HasValue ?
                new ObjectParameter("Id_PerfilUsuario", id_PerfilUsuario) :
                new ObjectParameter("Id_PerfilUsuario", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("modPerfilUsuario", perfil_IdParameter, usuarioParameter, id_PerfilUsuarioParameter);
        }
    
        public virtual int modProductos(Nullable<int> id_producto, string nombre, Nullable<int> tipo_producto, Nullable<int> precio, string descripcion)
        {
            var id_productoParameter = id_producto.HasValue ?
                new ObjectParameter("Id_producto", id_producto) :
                new ObjectParameter("Id_producto", typeof(int));
    
            var nombreParameter = nombre != null ?
                new ObjectParameter("Nombre", nombre) :
                new ObjectParameter("Nombre", typeof(string));
    
            var tipo_productoParameter = tipo_producto.HasValue ?
                new ObjectParameter("Tipo_producto", tipo_producto) :
                new ObjectParameter("Tipo_producto", typeof(int));
    
            var precioParameter = precio.HasValue ?
                new ObjectParameter("Precio", precio) :
                new ObjectParameter("Precio", typeof(int));
    
            var descripcionParameter = descripcion != null ?
                new ObjectParameter("Descripcion", descripcion) :
                new ObjectParameter("Descripcion", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("modProductos", id_productoParameter, nombreParameter, tipo_productoParameter, precioParameter, descripcionParameter);
        }
    
        public virtual int modProductosXcombo(Nullable<int> id_ProducXcombo, Nullable<int> id_combo, Nullable<int> id_producto)
        {
            var id_ProducXcomboParameter = id_ProducXcombo.HasValue ?
                new ObjectParameter("Id_ProducXcombo", id_ProducXcombo) :
                new ObjectParameter("Id_ProducXcombo", typeof(int));
    
            var id_comboParameter = id_combo.HasValue ?
                new ObjectParameter("Id_combo", id_combo) :
                new ObjectParameter("Id_combo", typeof(int));
    
            var id_productoParameter = id_producto.HasValue ?
                new ObjectParameter("Id_producto", id_producto) :
                new ObjectParameter("Id_producto", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("modProductosXcombo", id_ProducXcomboParameter, id_comboParameter, id_productoParameter);
        }
    
        public virtual int modProveedor(Nullable<int> idProveedor, string nombre, string apellido_1, string apellido_2, string telefono, string producto)
        {
            var idProveedorParameter = idProveedor.HasValue ?
                new ObjectParameter("IdProveedor", idProveedor) :
                new ObjectParameter("IdProveedor", typeof(int));
    
            var nombreParameter = nombre != null ?
                new ObjectParameter("Nombre", nombre) :
                new ObjectParameter("Nombre", typeof(string));
    
            var apellido_1Parameter = apellido_1 != null ?
                new ObjectParameter("Apellido_1", apellido_1) :
                new ObjectParameter("Apellido_1", typeof(string));
    
            var apellido_2Parameter = apellido_2 != null ?
                new ObjectParameter("Apellido_2", apellido_2) :
                new ObjectParameter("Apellido_2", typeof(string));
    
            var telefonoParameter = telefono != null ?
                new ObjectParameter("Telefono", telefono) :
                new ObjectParameter("Telefono", typeof(string));
    
            var productoParameter = producto != null ?
                new ObjectParameter("Producto", producto) :
                new ObjectParameter("Producto", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("modProveedor", idProveedorParameter, nombreParameter, apellido_1Parameter, apellido_2Parameter, telefonoParameter, productoParameter);
        }
    
        public virtual int modTipo_Combo(Nullable<int> id_tipo_combo, string nombre_tipo_com)
        {
            var id_tipo_comboParameter = id_tipo_combo.HasValue ?
                new ObjectParameter("Id_tipo_combo", id_tipo_combo) :
                new ObjectParameter("Id_tipo_combo", typeof(int));
    
            var nombre_tipo_comParameter = nombre_tipo_com != null ?
                new ObjectParameter("Nombre_tipo_com", nombre_tipo_com) :
                new ObjectParameter("Nombre_tipo_com", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("modTipo_Combo", id_tipo_comboParameter, nombre_tipo_comParameter);
        }
    
        public virtual int modTipo_Producto(Nullable<int> id_tipo_Producto, string nombre_tipo_pro)
        {
            var id_tipo_ProductoParameter = id_tipo_Producto.HasValue ?
                new ObjectParameter("Id_tipo_Producto", id_tipo_Producto) :
                new ObjectParameter("Id_tipo_Producto", typeof(int));
    
            var nombre_tipo_proParameter = nombre_tipo_pro != null ?
                new ObjectParameter("Nombre_tipo_pro", nombre_tipo_pro) :
                new ObjectParameter("Nombre_tipo_pro", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("modTipo_Producto", id_tipo_ProductoParameter, nombre_tipo_proParameter);
        }
    
        public virtual int modUsuario(string usuario, string contraseña, Nullable<int> estado)
        {
            var usuarioParameter = usuario != null ?
                new ObjectParameter("Usuario", usuario) :
                new ObjectParameter("Usuario", typeof(string));
    
            var contraseñaParameter = contraseña != null ?
                new ObjectParameter("Contraseña", contraseña) :
                new ObjectParameter("Contraseña", typeof(string));
    
            var estadoParameter = estado.HasValue ?
                new ObjectParameter("Estado", estado) :
                new ObjectParameter("Estado", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("modUsuario", usuarioParameter, contraseñaParameter, estadoParameter);
        }
    
        public virtual ObjectResult<Nullable<int>> ObtenerMesasActivas()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Nullable<int>>("ObtenerMesasActivas");
        }
    
        public virtual ObjectResult<ObtenerOrdenesDeMesa_Result> ObtenerOrdenesDeMesa(Nullable<int> mesa)
        {
            var mesaParameter = mesa.HasValue ?
                new ObjectParameter("mesa", mesa) :
                new ObjectParameter("mesa", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<ObtenerOrdenesDeMesa_Result>("ObtenerOrdenesDeMesa", mesaParameter);
        }
    
        public virtual ObjectResult<ObtenerProductosPorCategoria_Result> ObtenerProductosPorCategoria(Nullable<int> tipo_producto)
        {
            var tipo_productoParameter = tipo_producto.HasValue ?
                new ObjectParameter("Tipo_producto", tipo_producto) :
                new ObjectParameter("Tipo_producto", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<ObtenerProductosPorCategoria_Result>("ObtenerProductosPorCategoria", tipo_productoParameter);
        }
    
        public virtual ObjectResult<recCliente_Result> recCliente()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<recCliente_Result>("recCliente");
        }
    
        public virtual ObjectResult<recClientexId_Result> recClientexId(string telefono)
        {
            var telefonoParameter = telefono != null ?
                new ObjectParameter("Telefono", telefono) :
                new ObjectParameter("Telefono", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<recClientexId_Result>("recClientexId", telefonoParameter);
        }
    
        public virtual int recCombos()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("recCombos");
        }
    
        public virtual int recCombosxId(Nullable<int> id_combo)
        {
            var id_comboParameter = id_combo.HasValue ?
                new ObjectParameter("Id_combo", id_combo) :
                new ObjectParameter("Id_combo", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("recCombosxId", id_comboParameter);
        }
    
        public virtual ObjectResult<recDetalleOrden_Result> recDetalleOrden()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<recDetalleOrden_Result>("recDetalleOrden");
        }
    
        public virtual ObjectResult<recDetalleOrdenConOrdenEstado1_Result> recDetalleOrdenConOrdenEstado1()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<recDetalleOrdenConOrdenEstado1_Result>("recDetalleOrdenConOrdenEstado1");
        }
    
        public virtual ObjectResult<recDetalleOrdenxId_Result> recDetalleOrdenxId(Nullable<int> id_Detalle)
        {
            var id_DetalleParameter = id_Detalle.HasValue ?
                new ObjectParameter("Id_Detalle", id_Detalle) :
                new ObjectParameter("Id_Detalle", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<recDetalleOrdenxId_Result>("recDetalleOrdenxId", id_DetalleParameter);
        }
    
        public virtual ObjectResult<recEstados_Result> recEstados()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<recEstados_Result>("recEstados");
        }
    
        public virtual ObjectResult<recEstadoxId_Result> recEstadoxId(Nullable<int> id_Estado)
        {
            var id_EstadoParameter = id_Estado.HasValue ?
                new ObjectParameter("Id_Estado", id_Estado) :
                new ObjectParameter("Id_Estado", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<recEstadoxId_Result>("recEstadoxId", id_EstadoParameter);
        }
    
        public virtual ObjectResult<recFacturas_Result> recFacturas()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<recFacturas_Result>("recFacturas");
        }
    
        public virtual ObjectResult<recFacturaxId_Result> recFacturaxId(Nullable<int> id_Factura)
        {
            var id_FacturaParameter = id_Factura.HasValue ?
                new ObjectParameter("Id_Factura", id_Factura) :
                new ObjectParameter("Id_Factura", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<recFacturaxId_Result>("recFacturaxId", id_FacturaParameter);
        }
    
        public virtual ObjectResult<recIngredientes_Result> recIngredientes()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<recIngredientes_Result>("recIngredientes");
        }
    
        public virtual ObjectResult<recIngredientesXProducto_Result> recIngredientesXProducto()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<recIngredientesXProducto_Result>("recIngredientesXProducto");
        }
    
        public virtual ObjectResult<recIngredientexId_Result> recIngredientexId(Nullable<int> id_Ingrediente)
        {
            var id_IngredienteParameter = id_Ingrediente.HasValue ?
                new ObjectParameter("Id_Ingrediente", id_Ingrediente) :
                new ObjectParameter("Id_Ingrediente", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<recIngredientexId_Result>("recIngredientexId", id_IngredienteParameter);
        }
    
        public virtual ObjectResult<recIngredienteXProductoxId_Result> recIngredienteXProductoxId(Nullable<int> id_ingredienteXproducto)
        {
            var id_ingredienteXproductoParameter = id_ingredienteXproducto.HasValue ?
                new ObjectParameter("Id_ingredienteXproducto", id_ingredienteXproducto) :
                new ObjectParameter("Id_ingredienteXproducto", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<recIngredienteXProductoxId_Result>("recIngredienteXProductoxId", id_ingredienteXproductoParameter);
        }
    
        public virtual ObjectResult<recInventario_Result> recInventario()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<recInventario_Result>("recInventario");
        }
    
        public virtual ObjectResult<recInventarioxId_Result> recInventarioxId(Nullable<int> id_inventario)
        {
            var id_inventarioParameter = id_inventario.HasValue ?
                new ObjectParameter("Id_inventario", id_inventario) :
                new ObjectParameter("Id_inventario", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<recInventarioxId_Result>("recInventarioxId", id_inventarioParameter);
        }
    
        public virtual ObjectResult<recMesaPerfilxId_Result> recMesaPerfilxId(Nullable<int> perfil_Id)
        {
            var perfil_IdParameter = perfil_Id.HasValue ?
                new ObjectParameter("Perfil_Id", perfil_Id) :
                new ObjectParameter("Perfil_Id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<recMesaPerfilxId_Result>("recMesaPerfilxId", perfil_IdParameter);
        }
    
        public virtual ObjectResult<recMesas_Result> recMesas()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<recMesas_Result>("recMesas");
        }
    
        public virtual ObjectResult<Nullable<int>> recMesasActivasDO()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Nullable<int>>("recMesasActivasDO");
        }
    
        public virtual ObjectResult<recMesaxId_Result> recMesaxId(Nullable<int> id_Mesa)
        {
            var id_MesaParameter = id_Mesa.HasValue ?
                new ObjectParameter("Id_Mesa", id_Mesa) :
                new ObjectParameter("Id_Mesa", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<recMesaxId_Result>("recMesaxId", id_MesaParameter);
        }
    
        public virtual ObjectResult<Nullable<int>> recOrdenActivaXMesa(Nullable<int> id_Mesa)
        {
            var id_MesaParameter = id_Mesa.HasValue ?
                new ObjectParameter("Id_Mesa", id_Mesa) :
                new ObjectParameter("Id_Mesa", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Nullable<int>>("recOrdenActivaXMesa", id_MesaParameter);
        }
    
        public virtual ObjectResult<recOrdenes_Result> recOrdenes()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<recOrdenes_Result>("recOrdenes");
        }
    
        public virtual ObjectResult<recOrdenxId_Result> recOrdenxId(Nullable<int> id_Orden)
        {
            var id_OrdenParameter = id_Orden.HasValue ?
                new ObjectParameter("Id_Orden", id_Orden) :
                new ObjectParameter("Id_Orden", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<recOrdenxId_Result>("recOrdenxId", id_OrdenParameter);
        }
    
        public virtual ObjectResult<recPerfiles_Result> recPerfiles()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<recPerfiles_Result>("recPerfiles");
        }
    
        public virtual ObjectResult<recPerfilUsuario_Result> recPerfilUsuario()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<recPerfilUsuario_Result>("recPerfilUsuario");
        }
    
        public virtual ObjectResult<recPerfilUsuarioxId_Result> recPerfilUsuarioxId(Nullable<int> id_PerfilUsuario)
        {
            var id_PerfilUsuarioParameter = id_PerfilUsuario.HasValue ?
                new ObjectParameter("Id_PerfilUsuario", id_PerfilUsuario) :
                new ObjectParameter("Id_PerfilUsuario", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<recPerfilUsuarioxId_Result>("recPerfilUsuarioxId", id_PerfilUsuarioParameter);
        }
    
        public virtual ObjectResult<recProductos_Result> recProductos()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<recProductos_Result>("recProductos");
        }
    
        public virtual int recProductosXcombo()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("recProductosXcombo");
        }
    
        public virtual int recProductosXcomboxId(Nullable<int> id_ProducXcombo)
        {
            var id_ProducXcomboParameter = id_ProducXcombo.HasValue ?
                new ObjectParameter("Id_ProducXcombo", id_ProducXcombo) :
                new ObjectParameter("Id_ProducXcombo", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("recProductosXcomboxId", id_ProducXcomboParameter);
        }
    
        public virtual ObjectResult<recProductosxId_Result> recProductosxId(Nullable<int> id_producto)
        {
            var id_productoParameter = id_producto.HasValue ?
                new ObjectParameter("Id_producto", id_producto) :
                new ObjectParameter("Id_producto", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<recProductosxId_Result>("recProductosxId", id_productoParameter);
        }
    
        public virtual ObjectResult<recProveedor_Result> recProveedor()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<recProveedor_Result>("recProveedor");
        }
    
        public virtual ObjectResult<recProveedorxId_Result> recProveedorxId(Nullable<int> idProveedor)
        {
            var idProveedorParameter = idProveedor.HasValue ?
                new ObjectParameter("IdProveedor", idProveedor) :
                new ObjectParameter("IdProveedor", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<recProveedorxId_Result>("recProveedorxId", idProveedorParameter);
        }
    
        public virtual int recTipo_Combo()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("recTipo_Combo");
        }
    
        public virtual int recTipo_ComboxId(Nullable<int> id_tipo_combo)
        {
            var id_tipo_comboParameter = id_tipo_combo.HasValue ?
                new ObjectParameter("Id_tipo_combo", id_tipo_combo) :
                new ObjectParameter("Id_tipo_combo", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("recTipo_ComboxId", id_tipo_comboParameter);
        }
    
        public virtual ObjectResult<recTipo_Producto_Result> recTipo_Producto()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<recTipo_Producto_Result>("recTipo_Producto");
        }
    
        public virtual ObjectResult<recTipo_ProductoxId_Result> recTipo_ProductoxId(Nullable<int> id_tipo_Producto)
        {
            var id_tipo_ProductoParameter = id_tipo_Producto.HasValue ?
                new ObjectParameter("Id_tipo_Producto", id_tipo_Producto) :
                new ObjectParameter("Id_tipo_Producto", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<recTipo_ProductoxId_Result>("recTipo_ProductoxId", id_tipo_ProductoParameter);
        }
    
        public virtual ObjectResult<recUsuarios_Result> recUsuarios()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<recUsuarios_Result>("recUsuarios");
        }
    
        public virtual ObjectResult<recUsuarioxId_Result> recUsuarioxId(string usuario)
        {
            var usuarioParameter = usuario != null ?
                new ObjectParameter("Usuario", usuario) :
                new ObjectParameter("Usuario", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<recUsuarioxId_Result>("recUsuarioxId", usuarioParameter);
        }
    
        public virtual int sp_alterdiagram(string diagramname, Nullable<int> owner_id, Nullable<int> version, byte[] definition)
        {
            var diagramnameParameter = diagramname != null ?
                new ObjectParameter("diagramname", diagramname) :
                new ObjectParameter("diagramname", typeof(string));
    
            var owner_idParameter = owner_id.HasValue ?
                new ObjectParameter("owner_id", owner_id) :
                new ObjectParameter("owner_id", typeof(int));
    
            var versionParameter = version.HasValue ?
                new ObjectParameter("version", version) :
                new ObjectParameter("version", typeof(int));
    
            var definitionParameter = definition != null ?
                new ObjectParameter("definition", definition) :
                new ObjectParameter("definition", typeof(byte[]));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_alterdiagram", diagramnameParameter, owner_idParameter, versionParameter, definitionParameter);
        }
    
        public virtual int sp_creatediagram(string diagramname, Nullable<int> owner_id, Nullable<int> version, byte[] definition)
        {
            var diagramnameParameter = diagramname != null ?
                new ObjectParameter("diagramname", diagramname) :
                new ObjectParameter("diagramname", typeof(string));
    
            var owner_idParameter = owner_id.HasValue ?
                new ObjectParameter("owner_id", owner_id) :
                new ObjectParameter("owner_id", typeof(int));
    
            var versionParameter = version.HasValue ?
                new ObjectParameter("version", version) :
                new ObjectParameter("version", typeof(int));
    
            var definitionParameter = definition != null ?
                new ObjectParameter("definition", definition) :
                new ObjectParameter("definition", typeof(byte[]));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_creatediagram", diagramnameParameter, owner_idParameter, versionParameter, definitionParameter);
        }
    
        public virtual int sp_dropdiagram(string diagramname, Nullable<int> owner_id)
        {
            var diagramnameParameter = diagramname != null ?
                new ObjectParameter("diagramname", diagramname) :
                new ObjectParameter("diagramname", typeof(string));
    
            var owner_idParameter = owner_id.HasValue ?
                new ObjectParameter("owner_id", owner_id) :
                new ObjectParameter("owner_id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_dropdiagram", diagramnameParameter, owner_idParameter);
        }
    
        public virtual ObjectResult<sp_helpdiagramdefinition_Result> sp_helpdiagramdefinition(string diagramname, Nullable<int> owner_id)
        {
            var diagramnameParameter = diagramname != null ?
                new ObjectParameter("diagramname", diagramname) :
                new ObjectParameter("diagramname", typeof(string));
    
            var owner_idParameter = owner_id.HasValue ?
                new ObjectParameter("owner_id", owner_id) :
                new ObjectParameter("owner_id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_helpdiagramdefinition_Result>("sp_helpdiagramdefinition", diagramnameParameter, owner_idParameter);
        }
    
        public virtual ObjectResult<sp_helpdiagrams_Result> sp_helpdiagrams(string diagramname, Nullable<int> owner_id)
        {
            var diagramnameParameter = diagramname != null ?
                new ObjectParameter("diagramname", diagramname) :
                new ObjectParameter("diagramname", typeof(string));
    
            var owner_idParameter = owner_id.HasValue ?
                new ObjectParameter("owner_id", owner_id) :
                new ObjectParameter("owner_id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_helpdiagrams_Result>("sp_helpdiagrams", diagramnameParameter, owner_idParameter);
        }
    
        public virtual int sp_renamediagram(string diagramname, Nullable<int> owner_id, string new_diagramname)
        {
            var diagramnameParameter = diagramname != null ?
                new ObjectParameter("diagramname", diagramname) :
                new ObjectParameter("diagramname", typeof(string));
    
            var owner_idParameter = owner_id.HasValue ?
                new ObjectParameter("owner_id", owner_id) :
                new ObjectParameter("owner_id", typeof(int));
    
            var new_diagramnameParameter = new_diagramname != null ?
                new ObjectParameter("new_diagramname", new_diagramname) :
                new ObjectParameter("new_diagramname", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_renamediagram", diagramnameParameter, owner_idParameter, new_diagramnameParameter);
        }
    
        public virtual int sp_upgraddiagrams()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_upgraddiagrams");
        }
    }
}
